### ISSUE TITLE
UnsatisfiedLinkError: cannot find native jdk.internal.reflect.Reflection.getClassAccessFlags

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#106]
Runtime error "java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.reflect.Reflection.getClassAccessFlags" when running CountDownLatchTest

    [junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.reflect.Reflection.getClassAccessFlags
    [junit]     at jdk.internal.reflect.Reflection.getClassAccessFlags(gov.nasa.jpf.vm.JPF_jdk_internal_reflect_Reflection)
    [junit]     at sun.invoke.util.VerifyAccess.getClassModifiers(VerifyAccess.java:156)
    [junit]     at sun.invoke.util.VerifyAccess.isClassAccessible(VerifyAccess.java:177)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:2047)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2020)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)

The above error follows after the PR #104

**Comment by cyrille-artho** [comment]
As far as I can tell, JPF currently does not search inner classes (perhaps it should), so we can probably get away with delegating this to `Class.getModifiers()`.
The native peer for that method is `public int getModifiers____I (MJIEnv env, int clsRef)`.

**Comment by gayanW** [comment]
`Reflection#getClassAccessFlags(java.lang.Class)` is only called about twice for entire test units. I think it is safe to say that the `native int getClassAccessFlags(Class<?> c)` is never caleed with an inner class as the argument c, while running the tests.

I've tried the following implementation:

```
  /**
   * NativePeer method for {@link jdk.internal.reflect.Reflection#getClassAccessFlags(java.lang.Class)}
   */
  @MJI
  public static int getClassAccessFlags__Ljava_lang_Class_2__I(MJIEnv env, int clsObjRef, int cRef) {
    try {
      ClassInfo classInfo = env.getClassInfo(cRef);
      Class<?> c = Class.forName(classInfo.getName());
      return c.getModifiers();

    } catch (ClassNotFoundException e) {
      return MJIEnv.NULL;
    }
  }
```
But I'm not quite sure about the following code snippet:

      ClassInfo classInfo = env.getClassInfo(cRef);
      Class<?> c = Class.forName(classInfo.getName());

Is this the correct approach to retrieve a Class object associated with given class reference `(int cRef)`?

**Comment by cyrille-artho** [comment]
Yes, I meant the mechanism of searching super classes/interfaces for methods that cannot be found in the current class.

**Comment by cyrille-artho** [comment]
`ClassInfo classInfo = env.getClassInfo(cRef);
 Class<?> c = Class.forName(classInfo.getName());`

Thanks for asking. This would get the information about class `ClassInfo`, not the class that you're actually looking for. Instead, return the `modifiers` from `classInfo` itself:
`return classInfo.getModifiers();`
