### ISSUE TITLE
UnsatisfiedLinkError: cannot find native StackStreamFactory.checkStackWalkModes

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#113]
Runtime error _"java.lang.UnsatisfiedLinkError: cannot find native java.lang.StackStreamFactory.checkStackWalkModes"_ when running StackWalkerTest.

    [junit] java.lang.UnsatisfiedLinkError: cannot find native java.lang.StackStreamFactory.checkStackWalkModes
    [junit]     at java.lang.StackStreamFactory.checkStackWalkModes(no peer)
    [junit]     at java.lang.StackStreamFactory.init(StackStreamFactory.java:962)
    [junit]     at java.lang.StackStreamFactory.<clinit>(StackStreamFactory.java:66)
    [junit]     at java.lang.StackWalker.walk(StackWalker.java:497)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest$MyClass.foo(StackWalkerTest.java:41)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest$MyClass.bar(StackWalkerTest.java:31)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest.callIt(StackWalkerTest.java:62)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest.testCallerClass(StackWalkerTest.java:68)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

**Comment by gayanW** [comment]
Thank you for the suggestions. I don't see any other errors associated with StackStreamFactory in the current build logs. Please see the PR which implement just a native peer that returns true.

**Comment by cyrille-artho** [comment]
OK, let's close this issue for now and re-open it if there is a need for a fresh implementation of `StackWalker`. This might become necessary if its internal native methods do not work in jpf-core.

**Comment by gayanW** [comment]
Now I could see more UnsatisfiedLinkErrors related to native methods in StackStreamFactory, like:

    [junit] java.lang.UnsatisfiedLinkError: cannot find native java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk
    [junit]     at java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(no peer)
    [junit]     at java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:370)
    [junit]     at java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:243)
    [junit]     at java.lang.StackWalker.walk(StackWalker.java:498)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest$MyClass.foo(StackWalkerTest.java:41)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest$MyClass.bar(StackWalkerTest.java:31)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest.callIt(StackWalkerTest.java:62)
    [junit]     at gov.nasa.jpf.test.java.lang.StackWalkerTest.testCallerClass(StackWalkerTest.java:68)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

Maybe we could just revert #83, then refactor old ReflectionTest to use `jdk.internal.reflect.Reflection` instead of `sun.reflect.Reflection`. You may reopen the issue.

**Comment by cyrille-artho** [comment]
Still pending, even after PR #210.
