### ISSUE TITLE
JVMClassFileContainer#getModuleName should not throw RuntimeException

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#120]
https://github.com/javapathfinder/jpf-core/blob/5145473337b6ef74a59e257dd785253ec480f692/src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java#L107-L116

JVMClassFileContainer#getModuleName throws a JPFException if a class object associated with the given typeName is not found, thus terminating the whole class file checking process which should happen recursively.

Which affects tests like:

https://github.com/javapathfinder/jpf-core/blob/5145473337b6ef74a59e257dd785253ec480f692/src/tests/gov/nasa/jpf/test/java/lang/ClassLoaderTest.java#L55-L64

    [junit] Caused by: gov.nasa.jpf.JPFException: Class for typename non_existing_class not found
    [junit]     at gov.nasa.jpf.jvm.JVMClassFileContainer.getModuleName(JVMClassFileContainer.java:114)
    [junit]     at gov.nasa.jpf.jvm.JVMClassFileContainer.getClassEntryURL(JVMClassFileContainer.java:100)
    [junit]     at gov.nasa.jpf.jvm.DirClassFileContainer.getMatch(DirClassFileContainer.java:53)
    [junit]     at gov.nasa.jpf.vm.ClassPath.findMatch(ClassPath.java:105)
    [junit]     at gov.nasa.jpf.vm.ClassLoaderInfo.getMatch(ClassLoaderInfo.java:661)
    [junit]     at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:343)
    [junit]     at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
    [junit]     at gov.nasa.jpf.vm.JPF_java_lang_ClassLoader.findSystemClass__Ljava_lang_String_2__Ljava_lang_Class_2(JPF_java_lang_ClassLoader.java:122)

**Comment by cyrille-artho** [comment]
Why shouldn't an exception be thrown here? I don't quite see what's wrong with the existing behavior. Please explain.

**Comment by gayanW** [comment]
JVMClassFileContainer#getModuleName is used by getMatch methods in the ClassFileContainer types. When searching for a class,  getMatch is called for each and every container up until it finds the class file for the given type name. Only If the class for the given type name is not found (in all containers)  ClassNotFoundException should be thrown.

JVMClassFileContainer#getModuleName is a method I implemented recently which is used within getMatch. The former getMatch method only returns a ClassFileMatch or null in case no match is found.

**Comment by cyrille-artho** [comment]
I see. In that case, the new version is consistent. The test will succeed if a ClassNotFoundException is thrown at the top level.
