### ISSUE TITLE
CastException: ByteArrayFields to CharArrayFields in NativePeer method for String#equals

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#127]
"CastException: ByteArrayFields cannot be cast to CharArrayFields" in MJI native peer method for java.lang.String#equals

    [junit] Caused by: java.lang.ClassCastException: gov.nasa.jpf.vm.ByteArrayFields cannot be cast to gov.nasa.jpf.vm.CharArrayFields
    [junit]     at gov.nasa.jpf.vm.JPF_java_lang_String.equals__Ljava_lang_Object_2__Z(JPF_java_lang_String.java:187)

https://github.com/javapathfinder/jpf-core/blob/9f076bc2f73a1fc3ad04399376925ef84561dc43/src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java#L166-L200

It assumes the 'value' field  of both Strings to be CharArrayFields
https://github.com/javapathfinder/jpf-core/blob/9f076bc2f73a1fc3ad04399376925ef84561dc43/src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java#L183-L187

But there are cases in which the returned Fields are of type ByteArrayFields. So for instance it will throw a ClassCastException for following assertion:

```
char[] value= new char[] {'a','b','c','d','e'};
assert "abcdef".equals(new String(value)));
```

**Comment by cyrille-artho** [comment]
Maybe all strings are stored as ByteArrayFields now?
See: `http://www.baeldung.com/java-9-compact-string`
If the array type depends on when the string was created, then the contents of the arrays have to be converted.

**Comment by cyrille-artho** [comment]
I would convert one representation into the other one in that case.

--
Regards,
Cyrille Artho

**Comment by gayanW** [comment]
There are different approaches to fix this.

- By providing non-native implementation method for String#equals as done in the JDK source.

- Conversion from char[] arrays to byte[] and then comparing the two. We'd need consider `value` Fields type and their respective coder (encoding).

- Turn both JPF string references into VM String objects using gov.nasa.jpf.vm.MJIEnv#getStringObject and then comparing the two. 

First and third approaches seem quite easier to accomplish. Please let me know if one is better than the other.
