### ISSUE TITLE
List Gradle 4.x as dependency on Build,-Test,-Run or System Requirements wiki

### ISSUE THREAD

**Issue by lemmy** [javapathfinder/jpf-core#145]
Building with gradle 3.x - which is part of debian/ubuntu - results in obscure errors. With gradle 4.x (4.9 to be precise), the build works fine.

https://github.com/javapathfinder/jpf-core/wiki/Build,-Test,-Run
https://github.com/javapathfinder/jpf-core/wiki/System-requirements

**Comment by cyrille-artho** [comment]
I made a note in the former document. As we use `./gradle`, the right version is installed automatically, so there is no need to install gradle beforehand. (Due to this, I did not change the second wiki page.)
