### ISSUE TITLE
Improve annotation support

### ISSUE THREAD

**Issue by jtoman** [javapathfinder/jpf-core#150]
The current annotation system of JPF lacks the following features:

* Annotation-valued attributes are deeply broken
* Default value reflection isn't supported
* toString() does not support primitive fields or primitive arrays beside int, long, and boolean
* Attempting to access an annotation with primitive attributes that are not int, long, or boolean will not work. Ditto for arrays thereof
* Mising annotation definitions completely tank class loading (annotations with missing types should just be skipped)
* equals() and hashCode() do not work as expected

**Comment by cyrille-artho** [comment]
Thanks for providing this list. Are there are (unit) tests that show how these features don't work, or can existing unit tests be adapted to show that/
