### ISSUE TITLE
Arrays.get/setShort does not work

### ISSUE THREAD

**Issue by jtoman** [javapathfinder/jpf-core#151]
Nor does reflectively setting or getting a short field. MJIEnv (erroneously) forward get/setShortField to get/setIntField, which fails with a type mismatch error.

**Comment by cyrille-artho** [comment]
A (failing) unit test for that would be great.

**Comment by jtoman** [comment]
Hi @cyrille-artho this issues (and all the others I opened) will have PR's coming shortly which will include the unit tests.
