### ISSUE TITLE
CompileClassesJava failed

### ISSUE THREAD

**Issue by Roy-NJU** [javapathfinder/jpf-core#162]
Hi:
 I installed the jdk version 1.8.0_51 and the Gradle version 4.8. When I builded jpf, the following execeptions occured, how can I solve it?
> Task :compileClassesJava FAILED
/home/lugongzheng/projects/jpf/jpf-core/src/classes/java/lang/ClassLoader.java:29: 警告: CompoundEnumeration是内部专用 API, 可能会在未来发行版中删除
import sun.misc.CompoundEnumeration;
               ^
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:60: 错误: 找不到符号
  private static JavaOISAccess javaOISAccess;
                 ^
  符号:   类 JavaOISAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:61: 错误: 找不到符号
  private static JavaObjectInputStreamAccess javaObjectInputStreamAccess;
                 ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:142: 错误: 找不到符号
  public static JavaObjectInputStreamAccess getJavaObjectInputStreamAccess() {
                ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:151: 错误: 找不到符号
  public static void setJavaObjectInputStreamAccess(JavaObjectInputStreamAccess access) {
                                                    ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:162: 错误: 找不到符号
  public static void setJavaOISAccess(JavaOISAccess access) {
                                      ^
  符号:   类 JavaOISAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:166: 错误: 找不到符号
  public static JavaOISAccess getJavaOISAccess() {
                ^
  符号:   类 JavaOISAccess
  位置: 类 SharedSecrets
/home/lugongzheng/projects/jpf/jpf-core/src/classes/java/lang/ClassLoader.java:114: 警告: CompoundEnumeration是内部专用 API, 可能会在未来发行版中删除
    return new CompoundEnumeration<URL>(resEnum);
               ^
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:52: 警告: JavaUtilJarAccess是内部专用 API, 可能会在未来发行版中删除
  private static JavaUtilJarAccess javaUtilJarAccess;
                 ^
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:82: 警告: JavaUtilJarAccess是内部专用 API, 可能会在未来发行版中删除
  public static JavaUtilJarAccess javaUtilJarAccess() {
                ^
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/SharedSecrets.java:88: 警告: JavaUtilJarAccess是内部专用 API, 可能会在未来发行版中删除
  public static void setJavaUtilJarAccess(JavaUtilJarAccess access) {
                                          ^
/home/lugongzheng/projects/jpf/jpf-core/src/classes/sun/misc/JavaNetAccess.java:32: 警告: URLClassPath是内部专用 API, 可能会在未来发行版中删除
    URLClassPath getURLClassPath (URLClassLoader ucl);
    ^
6 个错误
6 个警告

FAILURE: Build failed with an exception.

**Comment by cyrille-artho** [comment]
You need a more recent build of Java 8, such as Java 8 u 151 (1.8.0_151). The latest release in that series is Java 8 u 181.
Work to support Java 10 and 11 is in progress, so for now, only Java 8 is supported.
