### ISSUE TITLE
Task :compileJava FAILED // FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by nohope91** [javapathfinder/jpf-core#169]
I got all the requirements for jpf-core in my Kali but when I run ( ./gradlew buildJars ) it stops at 12% and this is the log : 
./gradlew buildJars

> Task :compileJava
/root/Downloads/jpf-core/src/main/gov/nasa/jpf/vm/HashedAllocationContext.java:21: error: cannot find symbol
import sun.misc.SharedSecrets;
               ^
  symbol:   class SharedSecrets
  location: package sun.misc
/root/Downloads/jpf-core/src/main/gov/nasa/jpf/vm/HashedAllocationContext.java:22: error: cannot find symbol
import sun.misc.JavaLangAccess;
               ^
  symbol:   class JavaLangAccess
  location: package sun.misc
/root/Downloads/jpf-core/src/main/gov/nasa/jpf/vm/HashedAllocationContext.java:85: error: cannot find symbol
   static final JavaLangAccess JLA = SharedSecrets.getJavaLangAccess();
                ^
  symbol:   class JavaLangAccess
  location: class HashedAllocationContext
/root/Downloads/jpf-core/src/main/gov/nasa/jpf/vm/HashedAllocationContext.java:85: error: cannot find symbol
   static final JavaLangAccess JLA = SharedSecrets.getJavaLangAccess();
                                     ^
  symbol:   variable SharedSecrets
  location: class HashedAllocationContext
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

=================================================

On the other hand when I try to run ( ant ) it says : 
Buildfile: build.xml does not exist!
Build failed

What should I do ?????

I have all the Java & OpenJDK packages installed and my Kali is 100% up to date

**Comment by lassebe** [comment]
What Java version are you using? (`java --version`). 
If your version is 9 or greater, the classes that are mentioned in your error output are deprecated.
Could you try installing Java 8 and running the Gradle task again?
