### ISSUE TITLE
NoClassDefFoundError: sun/misc/SharedSecrets

### ISSUE THREAD

**Issue by ja2409** [javapathfinder/jpf-core#183]
Dear all,

I am trying to run JPF as described on these pages. I have successfully cloned the master branch, imported the project as gradle project and built the gradle project (using command line tool  gradlew.bat on windows). However, when I start JPF, e.g.:
"java -jar build/RunJPF.jar src/examples/HelloWorld.jpf"
there appears a [SEVERE] error:

[SEVERE] JPF configuration error: error instantiating class gov.nasa.jpf.vm.OVHeap for entry "vm.heap.class":
> exception in gov.nasa.jpf.vm.OVHeap(gov.nasa.jpf.Config,gov.nasa.jpf.vm.KernelState):
>> java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
> used within "vm.class" instantiation of class gov.nasa.jpf.vm.SingleProcessVM
[SEVERE] JPF terminated

The error appears regardless of the version of the code used (Java 8 + Ant or Java 11 + Gradle), and regardless of the environment (I have tried the new Eclipse (2019-03), NetBeans 8.2 and Apache NetBeans). I am working on Win 10.
I have checked, and the class SharedSecrets.class is indeed in the appropriate build folder.
Regarding configuration, I have set the site.properties file as described and using the default jpf.properties file for jpf-core. 
Please, any help would be nice. Thanks!

**Comment by ja2409** [comment]
Dear all, 

Just an update. I have successfully solved this by switching to an older version of Java JDK 1.8 that I had (u91), which JRE actually contains the class sun/misc/SharedSecrets. When using the older version, the compile failed on SharedSecrets file in JPF, but after deletion of the class, compile succeeded and verification was successfully started. 

Note that I was working on java-8 branch (with Ant). After building the jars, verification was successful for ANY version of Java 8 (even the newest one, i.e. u201). Verification was not successful, though, when Java was set to version 11 (the same error as described above appeared).

Hence,

**Comment by cyrille-artho** [comment]
Thanks. Java 11 is not yet supported; we have a branch `java-10` with work in progress. Getting Java 11 supported is indeed our top priority this summer!

**Comment by neharikapurieng** [comment]
Hi, 
I have a similar issue and I get the following error:

[SEVERE] JPF configuration error: error instantiating class gov.nasa.jpf.vm.OVHeap for entry "vm.heap.class":
> exception in gov.nasa.jpf.vm.OVHeap(gov.nasa.jpf.Config,gov.nasa.jpf.vm.KernelState):
>> java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
> used within "vm.class"

I am using jdk1.8.0_311 and jre1.8.0_311
