### ISSUE TITLE
NASA authentication error for using jpf

### ISSUE THREAD

**Issue by sadjadtalakoob74** [javapathfinder/jpf-core#195]
hi , 
recently by using this url in eclipse plugin management i get this error :

"Authentication failed for http://babelfish.arc.nasa.gov/trac/jpf/raw-attachment/wiki/projects/eclipse-jpf/update."

or when using the below address for clone : 
"$ hg clone http://babelfish.arc.nasa.gov/hg/jpf/jpf-core"

"http authorization required for https://babelfish.arc.nasa.gov/hg/jpf/jpf-core
realm"

is there any easy way to use jpf  asap ?

tnks

**Comment by gayanW** [comment]
Why not just get a copy of this repo?

**Comment by cyrille-artho** [comment]
Yes, version of JPF on babelfish is no longer maintained or accessible. This is the repository with the latest version. We would be grateful if someone updated the Eclipse plug-in with the URL of this repo.
