### ISSUE TITLE
A bug in java.lang.String.lastIndexOf

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#197]
There seems to be in issue with this native method in JPF_java_lang_String.java.
Found this bug when trying to use the BigInteger library with the following initialization:

`BigInteger bi = new BigInteger("-1");`

In the BigInteger constructor, the JPF's lastIndexOf() incorrectly returns -1 instead of 0 for:

`String val = "-1";
int index1 = val.lastIndexOf('-');`

This is caused by the following loop in the native method implementation of lastIndexOf() in JPF_java_lang_String.java.
Instead of: 

`for (int i = fromIndex; i > 0; i--) {
      if (values[i] == c) { return i; }
    }`

, it should have been ('>=' instead of '>'):

`for (int i = fromIndex; i >= 0; i--) {
      if (values[i] == c) { return i; }
    }`

This is the full method implementation:

    public int lastIndexOf__II__I (MJIEnv env, int objref, int c, int fromIndex) {
        int vref = env.getReferenceField(objref, "value");
        ElementInfo ei = env.getElementInfo(vref);
        char[] values = ((CharArrayFields) ei.getFields()).asCharArray();

        int len = values.length;

        if (fromIndex < 0) { return -1; }
        if (fromIndex > len - 1) {
            fromIndex = len - 1;
        }

        for (int i = fromIndex; i >= 0; i--) {
            if (values[i] == c) { return i; }
        }

        return -1;
    }

**Comment by cyrille-artho** [comment]
Thank you for this bug report; this is indeed a bug, and your analysis looks correct.
Would you like to create a unit test and fix (patch) for this? We can help you with that.
The best idea is to look at existing unit tests and then add a new one in this way:

```
@Test public void test... () {
  if (verifyNoPropertyViolation(){
    ... code to verify by JPF
  }
}
```

**Comment by rtrimana** [comment]
I would be happy to try that. Could you please guide me further?
I think I need to follow the pointers [here.](https://github.com/javapathfinder/jpf-core/wiki/Writing-JPF-tests)
And then I need to add that unit test [here.](https://github.com/javapathfinder/jpf-core/blob/master/src/tests/gov/nasa/jpf/test/java/lang/StringTest.java) 
Am I correct?

**Comment by cyrille-artho** [comment]
Yes, please add a unit test there.
You can change your one-liner to use an assertion:
```
String val = "-1";
assert(val.lastIndexOf('-') == 0); // test against off-by-one error (issue #197)
```
After this, you can make a pull request.
You make a pull request as follows:

1. Using the github web interface, fork this repository. This gives you your own version of the jpf-core repository.
2. Add the unit test. Make sure it works by trying `./gradlew test`.
3. Add and commit the test to the github repo (`git add`, `git commit`, `git push`).
4. After pushing, use the github web interface to make a pull request (from branch `master` in your repo) to branch `master` in the main repo.
