### ISSUE TITLE
Recursive ClassLoader.loadClass()

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#199]
I am suspecting that we might need a recursive structure in the `loadClassOnJPF (String typeName)` method that goes as follows:

      if (frame != null){ // there was a roundtrip, but make sure it wasn't a recursive one
        LoadClassRequest a = frame.getFrameAttr(LoadClassRequest.class);
        if (a != null && a.isRequestFor(typeName)){ // the roundtrip is completed
          int clsObjRef = frame.pop();

          if (clsObjRef == MJIEnv.NULL) {
            throw new ClassInfoException("class not found: " + typeName, this, "java.lang.NoClassDefFoundError", typeName);
          } else {
            return ti.getEnv().getReferredClassInfo(clsObjRef);
          }          
        }
      }
      // Recursive look-up before bailing out
      if (parent != null) {
        return parent.loadClass(typeName);
      }

      // initiate the roundtrip & bail out
      pushloadClassFrame(typeName);
      throw new LoadOnJPFRequired(typeName);

The reason is that I was trying to run the following Java class on JPF (using the library ASM 5.0.3): 

    import org.objectweb.asm.Opcodes;
    import org.objectweb.asm.ClassWriter;
    import org.objectweb.asm.MethodVisitor;
    
    import java.util.Map;
    import java.util.HashMap;
    
    public class SomeClassLoader extends ClassLoader implements Opcodes {
        private void loadMagic() {
            ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);
            cw.visit(Opcodes.V1_4, Opcodes.ACC_PUBLIC, "sun/reflect/SomeClass", null, "sun/reflect/SomeParentClass", null);
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(INVOKESPECIAL, "sun/reflect/SomeParentClass", "<init>", "()V", false);
            mv.visitInsn(RETURN);
            mv.visitMaxs(0,0);
            mv.visitEnd();
            cw.visitEnd();
    
            define(cw.toByteArray(), "sun.reflect.SomeClass");
        }
    
        protected void define(byte[] bytes, final String name) {
            //knownClasses.put(name, defineClass(name, bytes, 0, bytes.length));
            Class cls = defineClass(name, bytes, 0, bytes.length);
        }
    
        protected final Map<String,Class> knownClasses = new HashMap<String,Class>();
    
        public static void main(String[] args) {
            SunClassLoader sun = new SunClassLoader();
            sun.loadMagic();
        }
    }

and the `defineClass0()` method in the JPF_java_lang_ClassLoader class seems to return an empty/new ClassLoaderInfo object at this line:

`ClassLoaderInfo cl = env.getClassLoaderInfo(objRef);` 

Then the handle `cl` actually could not resolve the class I wanted to create (`sun/reflect/SomeClass`) because it could not find it anywhere. Even the `pathElements` in the ClassPath was also null for this new ClassLoaderInfo object. So, even when I provided the necessary classes in the paths I supplied to JPF (e.g., parent class `sun/reflect/SomeParentClass`), these classes weren't loaded properly into this ClassLoaderInfo object. And, the execution just bailed out as it was throwing the exception `LoadOnJPFRequired`.
Adding the recursive look-up would allow us to reach the SystemClassLoaderInfo object that has all information about the paths and resolved objects. This modification has allowed the above run to finish gracefully.

I got this inspiration from the original ClassLoader's `loadClass(String name, boolean resolve)` method that can be seen [here](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/ClassLoader.java).

If this understanding is wrong then perhaps I might have misunderstood the defineClass method implementation on JPF and perhaps there is some way to load the necessary classes without using the SystemClassLoaderInfo? Could someone please help?

**Comment by cyrille-artho** [comment]
Hi,
The class loader in JPF is indeed rather complex, and will become more complex for supporting Java 11 and later.
It is quite possible that `defineClass0` is a deliberate simplification that JPF deals with elsewhere, so that other mechanisms (such as the SystemClassLoader) take over in some cases by default.
You can find more information about the current class loader in:
https://yorkspace.library.yorku.ca/xmlui/bitstream/handle/10315/28190/Shafiei_Nastaran_2014_PhD.pdf?sequence=2&isAllowed=y
Page 
Chapter 4.1.2 (pages 93–101) describe the class loader.

Compared to the current implementation, I see that you have inserted the recursive lookup via parent. What is the effect of this on the unit tests, and on your example? If you can give us a short unit test that passes only with the recursive lookup, and no other unit test fails, then I'm happy to accept this change as a pull request.

**Comment by rtrimana** [comment]
Thank you! I actually posted the example code earlier, but without the real class names. But here they are:

    import org.objectweb.asm.Opcodes;
    import org.objectweb.asm.ClassWriter;
    import org.objectweb.asm.MethodVisitor;
    
    import java.util.Map;
    import java.util.HashMap;
    
    public class SunClassLoader extends ClassLoader implements Opcodes {
        private void loadMagic() {
            ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);
            cw.visit(Opcodes.V1_4, Opcodes.ACC_PUBLIC, "sun/reflect/GroovyMagic", null, "sun/reflect/MagicAccessorImpl", null);
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(INVOKESPECIAL, "sun/reflect/MagicAccessorImpl", "<init>", "()V", false);
            mv.visitInsn(RETURN);
            mv.visitMaxs(0,0);
            mv.visitEnd();
            cw.visitEnd();
    
            define(cw.toByteArray(), "sun.reflect.GroovyMagic");
        }
    
        protected void define(byte[] bytes, final String name) {
            //knownClasses.put(name, defineClass(name, bytes, 0, bytes.length));
            Class cls = defineClass(name, bytes, 0, bytes.length);
        }
    
        protected final Map<String,Class> knownClasses = new HashMap<String,Class>();
    
        public static void main(String[] args) {
            SunClassLoader sun = new SunClassLoader();
            sun.loadMagic();
        }
    }

So basically this code creates a ClassLoader object that does not contain anything on JPF (even no pathElements to look for the necessary libraries). When I tried this code on a standard JVM, it does pretty much the same thing:
1) SomeClassLoader that extends the ClassLoader class will instantiate a new ClassLoader object, then
2) The ClassLoader class will do a lookup for "sun/reflect/MagicAccessorImpl" and it does a recursive lookup through its parents. In JPF I think this is the SystemClassLoaderInfo object as the main parent of all ClassLoaderInfo objects.
In Shafiei's dissertation that you provided, it was actually mentioned that the standard ClassLoader implementation will do the lookup through the parents first (page 87 onward).

So, by applying the recursive lookup on JPF, this code was running fine but without it, it could not find the sun/reflect/MagicAccessorImpl class even though I put a model class in the correct path for JPF.
This code comes from the original Groovy library (with some modification to just test the defineClass() method). As you probably might have known earlier, I have been trying to make Groovy's bytecode run on JPF (if you look at my previous posts).

BTW, I noticed that there hasn't been any unit tests for the defineClass() method for JPF's java.lang.ClassLoader [here](https://github.com/javapathfinder/jpf-core/blob/master/src/tests/gov/nasa/jpf/test/java/lang/ClassLoaderTest.java). 
I would be happy to try to create a simpler unit test for this method based on your suggestions. But yeah, the above code is my current unit test. :)

**Comment by cyrille-artho** [comment]
I think the code above would make a good unit test, as long as there is a way to check the result of the class loading. I think you could try to find the class descriptor, and then check `methods.contains` to see if the inserted code is actually there.

**Comment by rtrimana** [comment]
So, my first proposal above apparently could break JPF's `java.net.URLClassLoader` implementation. Therefore, I decided to come up with the following proposal. 

1) The recursive look-up is attempted just in the native method `defineClass()` in the model class `JPF_java_lang_ClassLoader` through exception catching and handling. The look-up is attempted in the `SystemClassLoader` if the current `ClassLoader` fails to find the required classes. If the class still could not be found, the method would then throw a JPF's `java.lang.ClassNotFoundException` properly.

2) When the `ClassInfo` has been defined, we just return the necessary object reference number and not return a `LinkageError` exception as what it did before.

3) I have also created a unit test for the `defineClass()` method. All the unit tests have been run and they successfully passed.

4) There are a few minor changes in the build.gradle and jpf.properties files to download the necessary ASM library (for class writing), and get the right `classpath` for it.

I am submitting a `pull request` for these changes. Please let me know if you have any concerns with this proposal.

```
  @MJI
  public int defineClass0__Ljava_lang_String_2_3BII__Ljava_lang_Class_2(MJIEnv env, int objRef, int nameRef, int bufferRef, int offset, int length) {

    String cname = env.getStringObject(nameRef);
    ClassLoaderInfo cl = env.getClassLoaderInfo(objRef);

    // determine whether that the corresponding class is already defined by this
    // classloader, if so, just return the already defined class
    if (cl.getDefinedClassInfo(cname) != null) {  // attempt to define twice
      return cl.getDefinedClassInfo(cname).getClassObjectRef();
    }
        
    byte[] buffer = env.getByteArrayObject(bufferRef);
    
    try {
      ClassInfo ci = cl.getResolvedClassInfo( cname, buffer, offset, length);

      // Note: if the representation is not of a supported major or minor version, loading
      // throws an UnsupportedClassVersionError. But for now, we do not check for this here 
      // since we don't do much with minor and major versions

      ThreadInfo ti = env.getThreadInfo();
      ci.registerClass(ti);

      return ci.getClassObjectRef();

    } catch (LoadOnJPFRequired rre) {
      return searchThroughSystemClassLoader(env, objRef, nameRef, bufferRef, offset, length);

    } catch (ClassInfoException cix){
      if (cix.getExceptionClass().equals("java.lang.ClassNotFoundException")) {
        return searchThroughSystemClassLoader(env, objRef, nameRef, bufferRef, offset, length);
      }
      env.throwException("java.lang.ClassFormatError");
      return MJIEnv.NULL;

    }
  }
  
  private int searchThroughSystemClassLoader
          (MJIEnv env, int objRef, int nameRef, int bufferRef, int offset, int length) {

    int sysObjRef = env.getSystemClassLoaderInfo().getClassLoaderObjectRef();
    if (objRef != sysObjRef) {
      return defineClass0__Ljava_lang_String_2_3BII__Ljava_lang_Class_2
              (env, sysObjRef, nameRef, bufferRef, offset, length);
    }
    env.throwException("java.lang.ClassNotFoundException");
    return MJIEnv.NULL;
  }
```

**Comment by rtrimana** [comment]
Closing this issue as a patch has been created, reviewed, approved, and added to the master branch.

https://github.com/javapathfinder/jpf-core/pull/203
