### ISSUE TITLE
A bug in gov.nasa.jpf.vm.Types.getClassNameFromTypeName()

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#204]
A bug was found in `gov.nasa.jpf.vm.Types.getClassNameFromTypeName()` for the following code.

```
Class cls2 = Class.forName("groovy.runtime.metaclass.[Ljava.lang.Object;MetaClass");
```

This should have generated the following `ClassNotFoundException `on a standard JVM:

```
Exception in thread "main" java.lang.ClassNotFoundException: groovy/runtime/metaclass/[Ljava/lang/Object;MetaClass
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
```

On JPF this `Class.forName()` would have generated no error as JPF would successfully load the class. The root-cause is in the `Types.getClassNameFromTypeName()` method that actually only checks for the first occurrences of square brackets to parse class names of array type.

`int i=typeName.indexOf('['); // line 764 in Types.java`

Then it would result in a really bizarre class name: `[Lgroovy.runtime.metaclass.;` that does not even exist in the current context of the program.

Then when `ClassLoaderInfo.getResolvedClassInfo()` is called (below code), the `ClassInfo.isBuiltinClass( typeName)` would return `true` and `ci = loadSystemClass( typeName);` would create a new `ClassInfo` object for this new invalid class.

```
  public ClassInfo getResolvedClassInfo (String className) throws ClassInfoException {
    String typeName = Types.getClassNameFromTypeName( className);
    
    ClassInfo ci = resolvedClasses.get( typeName);
    if (ci == null) {
      if (ClassInfo.isBuiltinClass( typeName)){
        ci = loadSystemClass( typeName);

      } else {
        ...
```

My proposal is to change line 764 in `Types.java` into the following:

`int i=typeName.indexOf("[]"); // proposal for line 764 in Types.java`

As soon as this is confirmed, I will create the necessary patch for `Types.java` and the above `Class.forName()` method call as a unit test. Thank you.

**Comment by cyrille-artho** [comment]
Thanks for looking into this, and sorry for the late response.
The encoding of array types in bytecode is a bit weird; there is a `[` but no `]` in the bytecode type name.
Hence, your change may impact the parsing of correct array types, even though there is currently no regression test for that, it seems.
Look at the code a few lines below:
```
      for (int j=i; (j=typeName.indexOf('[',j+1)) >0;){
```
As you can see, `'['` is correct, and `"[]"` would not work with Java bytecode array types.

I admit that the code in `getClassNameFromTypeName` is not very elegant, and the comment is probably wrong; to me, it should be `[` in the comment instead of `[]`. Furthermore, the type name in your example is not valid and should result in an exception.

However, it seems that currently, the reason why JPF arrives at an exception (with your patch) or finds a strange class (without the patch) is wrong; we probably have to dig deeper to fix this.

**Comment by rtrimana** [comment]
I am completely aware of that weird bytecode notation that only uses one bracket, i.e., `'['` instead of `"[]"`. However, in that method `getClassNameFromTypeName()`, the bytecode notation has been handled by the following code block that comes right before the line of code I proposed to change.

This is from the method's lines 754 - 762 (please see [here](https://github.com/javapathfinder/jpf-core/blob/master/src/main/gov/nasa/jpf/vm/Types.java)):
```
    if (typeName.charAt(0) == '['){ // the "[<type>" notation
      if (typeName.charAt(1) == 'L'){
        if (typeName.charAt(n) != ';'){
          typeName = typeName + ';';
        }
      }
      
      return typeName;
    }
```
I believe this block will just return the `typeName` for inputs like `[Ljava.lang.Object;` or `[Ljava.lang.Object` where it's going to add a `';'` in the third if-statement.

Right after this code block we have the following checks now:

```
    int i=typeName.indexOf('[');
    if (i>0){ // the sort of "<type>[]"
      StringBuilder sb = new StringBuilder();
...
```
So, running a more complex program and stepping into the if-statement above has allowed me to see that the sorts of types that get here are like `byte[]`, `java.lang.Object[]`, `java.math.BigInteger[]`, `long[]`, `double[]`, etc. Therefore, the comment at that line (`// the sort of "<type>[]"`) is already correct. What wasn't precise was the implementation that simplified the case by just checking the opening bracket and not both brackets. While this may have worked for common Java programs in general and it might be a lot faster than checking both brackets as a String, apparently a big code like the Groovy library has that weird type passed into methods like `Class.forName()`, namely `groovy.runtime.metaclass.[Ljava.lang.Object;MetaClass`. This is not even the correct syntax according to the standard Java bytecode notation and I think that's why the person who coded this part might have missed that. 

A bit more on this. What Groovy does is really a lot of reflections and the runtime library forms class names on the fly. So the valid class names for this type of scenario are, for example, 

`groovy.runtime.metaclass.ClosureMetaClass`
`groovy.runtime.metaclass.MixedInMetaClass`
etc.
So, `groovy.runtime.metaclass.[Ljava.lang.Object;MetaClass` was generated because Groovy could not find the right MetaClass name on-the-fly and it just inserted `[Ljava.lang.Object;` there and the String object got passed into `Class.forName()`. I compared it with the standard Groovy run that would return a `java.lang.ClassNotFoundException` and the next lines in the code is meant to deal with this situation. When JPF didn't throw any exceptions because it missed it in the checks, it brought the execution path to another direction that caused unexpected errors on the Groovy side. That's why I am completely aware that this is really a super rare scenario. 

Therefore, I believe I don't stand corrected in this case. :) Hope this long explanation makes more sense to you. Please let me know what you think.

**Comment by cyrille-artho** [comment]
I see. So `forName` can mix Java and bytecode class name notations. (A bit messy IMHO...)
In that case, your patch is correct.

**Comment by rtrimana** [comment]
I agree. But perhaps that's just because that method is used to handle both bytecode and Java notations. I think we are doing a lot of those conversions between the two notations in `Types.java`. Based on my observations, both are often handled in one method.
