### ISSUE TITLE
Different exceptions thrown in ClassLoader.loadClass()

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#205]
Found a different exception thrown in ClassLoader.loadClass() using the following code:

```
Class cls = Object[].class;
Object obj = Introspector.getBeanInfo(cls);
```

On JPF:

```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoClassDefFoundError: IllegalName: [Ljava.lang.Object;BeanInfo
	at java.lang.ClassLoader.findSystemClass(gov.nasa.jpf.vm.JPF_java_lang_ClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:172)
	at java.lang.Class.forName(Class.java:219)
	at com.sun.beans.finder.ClassFinder.findClass(ClassFinder.java:103)
	at com.sun.beans.finder.InstanceFinder.instantiate(InstanceFinder.java:93)
	at com.sun.beans.finder.InstanceFinder.find(InstanceFinder.java:66)
	at java.beans.Introspector.findExplicitBeanInfo(Introspector.java:448)
	at java.beans.Introspector.<init>(Introspector.java:398)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at Reflection.main(Reflection.java:72)
```

On a standard JVM this will not be a problem because when `com.sun.beans.finder.ClassFinder.findClass` calls `java.lang.Class.forName`, the exception returned was a `ClassNotFoundException`. This exception would then be handled properly by the `java.beans.Introspector` class.

This difference is caused by the current implementation for `findSystemClass()` in JPF that throws `java.lang.NoClassDefFoundError` immediately after checking and finding illegal names for system class files (oversimplifying the myriad of cases for class loading handled by the standard JVM), whereas the standard `ClassLoader` library will actually check if the class has been first pre-loaded and its definition cannot be found during the call of the `loadClass()` method. Hence, the different exception names: NoClassDefFoundError vs. ClassNotFoundException.

I do have a simple proposal for changing this behavior (not widely tested yet though), but please confirm that we need to fix this. To me this problem is concerning and it needs to be fixed because java.beans.Introspector is a standard Java library.

**Comment by cyrille-artho** [comment]
Thank you for observing this. Any fix that does not break the current unit tests (or has fixes to failing tests), and which improves the behavior w.r.t. the standard JVM, is welcome.
As usual, fixes should have at least one unit test with them to prevent regressions.

**Comment by cyrille-artho** [comment]
This also seems to be related to #204 , in which some incorrect type names get accepted by JPF rather than rejected.

**Comment by rtrimana** [comment]
Yes, that's true. However, this case will need a different kind of fix. I will do another pull request as soon as we settle the pull request for #204.
