### ISSUE TITLE
Unused variables in multiple Classes

### ISSUE THREAD

**Issue by soumyadip007** [javapathfinder/jpf-core#217]
1. Config
T[] newInstance = (T[]) Array.newInstance(type, ids.length);
	T[] arr = newInstance;
and many classes.

**Comment by cyrille-artho** [comment]
I'm not sure if I can follow; in "Config", `arr` is used only in `getGroupInstances`, where it is returned. So it is used.
Can you please give us a successful patch that removes unused code?
