### ISSUE TITLE
Problem during installation in eclipse

### ISSUE THREAD

**Issue by vinayak-tyagi** [javapathfinder/jpf-core#218]
Hello,
I had tried to install the JPF-core into eclipse (Version: 2019-12 (4.14.0)) with JDK = 1.8.0_241 can anyone tell me what does it mean and how do I correct it ??
```
......................................... testing testOutOfBounds()
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: 2264
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: 1256
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: -1
......................................... testOutOfBounds: Ok

......................................... testing testBasic()
......................................... testBasic: Ok

......................................... testing testEnumeration()
......................................... testEnumeration: Ok

......................................... execution of testsuite: gov.nasa.jpf.util.BitSet1024Test SUCCEEDED
.... [1] testOutOfBounds: Ok
.... [2] testBasic: Ok
.... [3] testEnumeration: Ok
......................................... tests: 3, failures: 0, errors: 0
```

**Comment by ranjsa** [comment]
@vinayak-tyagi  This are some test cases on gov.nasa.jpf.util.**BitSet1024**  class which is used for maximizing performance (You can know more about this class from here-> https://pasteboard.co/IYqTHy1.png) . Well I don't think there is anything to worry about here because all three test cases have successfully passed.

Am i right @cyrille-artho ?

**Comment by cyrille-artho** [comment]
Yes, the test cases are functionally correct.
It may be desirable to eliminate any console output in the unit tests, though. It's better if the exception string is checked against the expected content in an assertion instead.

**Comment by ranjsa** [comment]
@cyrille-artho 
Can i work on this ?

**Comment by cyrille-artho** [comment]
Yes, I'm not aware of anyone else working on that problem, so please go ahead.

**Comment by vinayak-tyagi** [comment]
Thanks @cyrille-artho & @ranjsa
