### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ranjsa** [javapathfinder/jpf-core#220]
@cyrille-artho 
When i run gradle **verification** task it is failing in 6 testsCases One of which was in 
ClassLoaderTest. testGetResourceAsStream

![new issue#1](https://user-images.githubusercontent.com/43692789/76410714-68b34c00-63b6-11ea-82b5-6674bec39ff5.PNG)

I checked it is because of loding of this class **DiningPhil.class** (at line 187) which is no longer available in the project 

![new issue#2](https://user-images.githubusercontent.com/43692789/76410902-b8921300-63b6-11ea-9280-5896b111be92.PNG)

There are also similar errors like this 
Can i work on a patch of removing this kind of test cases ...which are causing build errors ?

**Comment by cyrille-artho** [comment]
Hi,
Please check first if there are older revisions where these tests pass. You can use `git bisect` for that. The file still exists but perhaps it was moved, and this test is not included in `./gradlew check` which is run in our Travis CI setup.
It is possible that we can fix this test and also fix the issue that prevents it from being run as part of the CI check, in which case we can strengthen to CI test suite.

**Comment by ranjsa** [comment]
@cyrille-artho 
Hi,
Thanks for helping 
I fixed those test cases which were failing in my system it was causing because i was using jdk version 11 for building this projects  ...But after using jdk version 8 i got all test cases passed in `./gradlew check` script and in travis ci.

it was realy great i got to know a lot about GRADLE, TRAVIS CI and jpf-core in this 3 days.
I think there is no need to keep this issue open So i am closing this issue now.
