### ISSUE TITLE
JPF listener fails to retrieve path data details when executed from unit test

### ISSUE THREAD

**Issue by ZephyrL** [javapathfinder/jpf-core#224]
Hi, 

I created a new listener that exports an error path as a JSON file. I also make a unit test to check whether the same output could be obtained for each run. But the problem is, the step information (of the transitions) of a path are retrieved in a common run, however, the output from the unit test doesn't contain the information of steps

I fork jpf-core and push a bug report [here: https://github.com/ZephyrL/jpf-core](https://github.com/ZephyrL/jpf-core)

By modifying the listener in Racer.jpf to my listener, and run the command

> java -jar build/RunJPF.jar src/examples/RacerJson.jpf

then the JSON file is produced in the root folder. A sample of the result (reproducible) could be found in **src/resources** folder, called **Racer.json.checked**

The unit test defined in gov.nasa.jpf.test.mc.basic.JsonOutputTest is expected to run the same code of "Racer" example, exporting the error as a JSON file, and then compare the output with the checked file. 

The test is run with either of the two following commands:

> bin/test gov.nasa.jpf.test.mc.basic.JsonOutputTest testJsonOutput

> ./gradlew test --tests JsonOutputTest

In the checked file, steps of transitions are recorded and exported completely, while the output of the unit test doesn't.

I was calling the method **step.getLineString()** and then output e.g. the source code of the step, but the return value of this method is always null when running the unit test.

**Comment by cyrille-artho** [comment]
Thanks for the bug report. It is good to note that when running this as a unit test, the resulting Path data structure is half-way complete: The number of transitions (and their top-level information such as the thread involved in each transition) is correct. Detailed information inside a transition is missing, though.
