### ISSUE TITLE
Method dispatch error

### ISSUE THREAD

**Issue by amgad-rady** [javapathfinder/jpf-core#248]
JPF's inheritance semantics ignores the private method modifier. Consider the following code snippet

```lang=java
class X {
  public int return7() {return f();}

  private int f() {return 7;}
}

class Y extends X {
  public int f() {return 8;}
}

public class Dispatch {
  public static void main(String[] args) {
    System.out.println((new Y()).return7());
  }
}
````

Running this in the JVM returns 7, while running it in JPF returns 8. JPF is not conforming to the dynamic method lookup algorithm described in section 15.12.4.4 of the JLS11.

**Comment by sonukushwaha403** [comment]
@amgad-rady , according  to me jvm returns the correct one ie 7

**Comment by sonukushwaha403** [comment]
can i know which file/folder has this issue  #248

**Comment by amgad-rady** [comment]
> can i know which file/folder has this issue #248

Verifying this code with JPF in the java-10-gradle branch will print 8.

**Comment by amgad-rady** [comment]
> can i know which file/folder has this issue #248

Verifying the posted code with Java 11 in the java-10-gradle branch prints 8 instead of 7. As for where the error originates, I'm not sure yet. I suspect it's in the native peer JPF_java_lang_reflect_Method, specifically in the "invoke" method.

**Comment by sonukushwaha403** [comment]
@amgad-rady sorry i am unable to locate the issue file ,please send me the dir location of #248 issue.

**Comment by DhirajSardar** [comment]
Is this issue still open ?

**Comment by cyrille-artho** [comment]
@quadhier : Thank you for confirming that this issue and several others can now be closed.
