### ISSUE TITLE
Incorrect serialization of lambda expressions

### ISSUE THREAD

**Issue by amgad-rady** [javapathfinder/jpf-core#255]
JPF does not correctly handle the FLAG_SERIALIZABLE field of java.lang.invoke.LambdaMetaFactory. Certain serializable lambda expressions, like those in java.util.Comparator, do not have the interface java.io.Serializable in their set of interfaces. The following test will fail

```lang=java
  @Test
  public void testComparingInt() {
    if (verifyNoPropertyViolation()) {
      ToIntFunction<Integer> keyExtractor = (x) -> 0;
      Comparator<Integer> comparator = comparingInt(keyExtractor);
    }
  }
```

**Comment by saksham9656** [comment]
hi would you please tell me more about it.
