### ISSUE TITLE
JPF listener interface modifications

### ISSUE THREAD

**Issue by adityakapre** [javapathfinder/jpf-core#270]
In the past interface, while implementing a listener, I was using `vm.getLastInstruction()` where `vm` was object of class `JVM` while implementing a listener interface method having declaration like `public void instructionExecuted(JVM vm)`

The new declaration is 
`public void instructionExecuted(VM vm, ThreadInfo currentThread, Instruction nextInstruction, Instruction executedInstruction)`

Is  `executedInstruction`  same as `vm.getLastInstruction()`  from the old interface ?

Following are other such usages of former `vm` object of `JVM` class that I am trying to refactor since the newer `VM` class does not declare those methods:

`vm.getLastMethodInfo()`
`vm.getLastElementInfo()`
`vm.getLastThreadInfo()`
`vm.getMainClassName()`
`vm.getLastClassInfo()`

What would correct refactor look like ?

**Comment by cyrille-artho** [comment]
You can "walk though" the hierarchy of getters in `Instruction` and `VM` to get the other information you need, e.g., 
`public MethodInfo getMethodInfo`, and `public ThreadInfo getCurrentThread` in `VM`. You will have to search a bit through the sources of JPF to find out how to refactor all of the details.
It is better to use the JPF Google Group to ask for help: https://groups.google.com/g/java-pathfinder
The issue tracker is best suited to report bugs or suggest concrete improvements (in JPF or its documentation).
