### ISSUE TITLE
Link Is not working Right Now

### ISSUE THREAD

**Issue by Jaikishan-Saroj-786** [javapathfinder/jpf-core#272]
commit  all the projects file into jpf-core respiratory and you can also make a new respiratory to working the link given below.
http://babelfish.arc.nasa.gov/hg/jpf/eclipse-jpf%60

**Comment by cyrille-artho** [comment]
This project no longer exists. Could you please post the URL of the page that contains the link, so I can remove that part of the text? (We would of course be very happy if someone contributed a new plugin.)

**Comment by Jaikishan-Saroj-786** [comment]
i thought this projects is not exist right now. sorry for in conveinence.
