### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by MPSINGH5** [javapathfinder/jpf-core#281]
@cyrille-artho I was trying to run JPF using Netbeans plugin but when I tried to build it on Gradle , it is giving message that the build failed because some deprecated Gradle features were used in the project.
@cyrille-artho  Please help me

**Comment by cyrille-artho** [comment]
We use the gradle wrapper `./gradlew` for our project.
Please build JPF from the command line or try to update the build file.
Of course, if you can port our build file to Gradle 7.0, we will gladly accept the patch.

**Comment by MPSINGH5** [comment]
okay I wil try to do the patch.
