### ISSUE TITLE
The type sun.net.www.protocol.https.Handler is not accessible

### ISSUE THREAD

**Issue by shadowasphodel2919** [javapathfinder/jpf-core#282]
I am working on `java-10-gradle` using 
> echo %JAVA_HOME%
C:\Program Files\Java\openlogic-openjdk-11.0.8+10-win-x64
java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

After running checks `CachedROHttpConnection.java` shows this  error
> The type sun.net.www.protocol.https.Handler is not accessible

I needed a suggestion on whether do I need to install Handler classes separately or do I need to change my java version?
Previously I was using this java version which was unable to run the test https://github.com/javapathfinder/jpf-core/issues/276#issuecomment-745353438

**Comment by cyrille-artho** [comment]
Your Java version as recognized by the command line (`java -version`) and your Java version as configured by `JAVA_HOME` are different. Try setting the `PATH` variable so that `java -version` also shows Java 11 (it is Java 8 right now on your system).
