### ISSUE TITLE
`java.lang.reflect.Method.invoke` should also accept subclasses of parameters

### ISSUE THREAD

**Issue by alexchang8** [javapathfinder/jpf-core#291]
Currently vm reflection method invocation only allows for the method to be called with the exact class. This is due to these lines: 
https://github.com/javapathfinder/jpf-core/blob/7e63ebf36369f63a1ddfac7374e7defeb948c8fe/src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Method.java#L462-L464

Subclasses should also be allowed here: for example, `public void foo(Number n)` can be invoked using reflection with either a `Number` or an `Integer`.

**Comment by cyrille-artho** [comment]
Do you have a unit test for this? It looks to me like `isInstanceOf` also permits subclassing.

**Comment by atishay5203** [comment]
@alexchang8 @gaurangkudale I want to work on this issue.

**Comment by cyrille-artho** [comment]
@atishay5203 : Please go ahead. The best way to work on this is to create a test case that works on the normal JVM but fails on the current version of Java Pathfinder. Once you have such a test, you can try to modify the code at line 462.

**Comment by alexchang8** [comment]
Thanks all for looking into this, seems this is not an issue so let’s go ahead and close!
