### ISSUE TITLE
`java.lang.ThreadLocal.withInitial` method missing

### ISSUE THREAD

**Issue by alexchang8** [javapathfinder/jpf-core#292]
The static method `java.lang.ThreadLocal.withInitial` (added in JDK 1.8) is currently missing. This can be fixed by adding

```
  public static <S> ThreadLocal<S> withInitial(Supplier<? extends S> supplier) {
    return new SuppliedThreadLocal<>(supplier);
  }
```

to ThreadLocal here https://github.com/javapathfinder/jpf-core/blob/7e63ebf36369f63a1ddfac7374e7defeb948c8fe/src/classes/java/lang/ThreadLocal.java#L98-L100

**Comment by cyrille-artho** [comment]
Can you please add this together with a unit test and make a pull request?

**Comment by gaurangkudale** [comment]
Hey @cyrille-artho created pull request please look into it
