### ISSUE TITLE
Improve .gitignore

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#3]
These files appear on my `git status` as untracked files   .
```
modified:   .idea/misc.xml
modified:   .idea/vcs.xml
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/ant.xml
```
It will be convenient if it ignores all the auto-generated and IDE specific files.

**Comment by cyrille-artho** [comment]
I think the goal was not to remove _all* IntelliJ-specific configuration files.
However, given that our build changes now, and will change again soon, I agree it is better to remove this completely for now.
Later on, someone can add IntelliJ support again for Java 10 or 11.
