### ISSUE TITLE
About JPF detects data Race

### ISSUE THREAD

**Issue by ppoooo0** [javapathfinder/jpf-core#300]
Hello, I am running a program with a concurrent defect, but the output of the program does not allow me to determine what the specific type of concurrent defect is for the program?What parameters should I add or modify to show the specific defect type?

**Comment by ppoooo0** [comment]
Hello, because of the following statement, it can only detect the first data race in the program, also want to ask how to display all possible data race in the program.
listener=gov.nasa.jpf.listener.PreciseRaceDetector




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "javapathfinder/jpf-core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月27日(星期三) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [javapathfinder/jpf-core] About JPF detects data Race (Issue #300)





 
If you add the following line to your .jpf configuration file, JPF will stop when detection the first data race within an execution:
 listener=gov.nasa.jpf.listener.PreciseRaceDetector  
The built-in properties already include deadlocks and assertion failures, so if one of these happen, the error message already indicates that.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cyrille-artho** [comment]
You can try the option `+search.multiple_errors=true`, but this may yield a lot of (similar?) traces that may relate to the same error. This option is not as well tested as the default that stops at the first error.
Please let us know if you encounter behavior with this option that suggests a bug in JPF (such as a stack trace within JPF itself, which would obviously be a bug).

**Comment by ppoooo0** [comment]
Hello, I tried to set search.multiple_errors to true, but still only one data race problem was looped in while checking.Finally, an error will be reported.Now I don't know how to get the program output to detect all the data contention issues.Finally, thank you very much for your reply.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "javapathfinder/jpf-core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [javapathfinder/jpf-core] About JPF detects data Race (Issue #300)





 
You can try the option +search.multiple_errors=true, but this may yield a lot of (similar?) traces that may relate to the same error. This option is not as well tested as the default that stops at the first error.
 Please let us know if you encounter behavior with this option that suggests a bug in JPF (such as a stack trace within JPF itself, which would obviously be a bug).
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
