### ISSUE TITLE
getting error while running gradlew command

### ISSUE THREAD

**Issue by gaurangkudale** [javapathfinder/jpf-core#318]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\gaura\jpf\jpf-core\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'jpf-core'.
> Could not find method testCompile() for arguments [org.ow2.asm:asm:7.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

**Comment by gaurangkudale** [comment]
Hi @cyrille-artho 
I'm getting this error while trying to run gradlew command on my muchine

**Comment by cyrille-artho** [comment]
Can you please post the whole report?
Are you using a newer version of gradle than the one we typically use?
If you use the wrapper with `./gradlew` (note the "w"), it will use a specific version of gradle which we have also tested.
Also, make sure you use Java 8 for the main branch and Java 11 for branch `java-10-gradle`.

**Comment by gaurangkudale** [comment]
1. The gradle version which I'm using is 7.3.1
2. Yes I am using java 8
I'll post a whole report

**Comment by gaurangkudale** [comment]
[https://drive.google.com/file/d/1R6DloFqQZSpIlQnKfCi2BMsHHEgOnpG_/view?usp=sharing](url)
report

**Comment by sroopsai** [comment]
1. Did you try to run `./gradlew` wrapper.

**Comment by gaurangkudale** [comment]
Hi @cyrille-artho 
when I restart my machine and ran the same command at that time I was not getting any errors besides that some tests were falling now I guess you can close this issue and Is there any update or changes needed in Gradle I can do that as well

**Comment by gaurangkudale** [comment]
Any updates?

**Comment by sroopsai** [comment]
Maybe it can lead to lot of issues if you update it to 7.3.3

**Comment by cyrille-artho** [comment]
If you use the Gradle wrapper `./gradlew`, then you are using the same version for Gradle that everyone else uses with JPF. This is supposed to work.
If you use a different version of Gradle (with `gradle`), then you might run into problems.
If you manage to port the current build to a newer version of Gradle, that is very welcome; we will accept PRs that upgrade Gradle as long as it works both on the `master` branch and on branch `jpf-10-gradle`.
