### ISSUE TITLE
Failed to build JPF with Java 17 

### ISSUE THREAD

**Issue by MariaSalim** [javapathfinder/jpf-core#322]
Hi everyone!

I am trying to install JPF. For that, I installed gradle version 7.4.1 and I have JVM 17. 

        ./gradlew buildJars 

Running this command in Windows powershell gives the following error: 
        

        FAILURE: Build failed with an exception.
        * Where:
        Settings file 'D:\Projects\EclipseProjects\jpf-core\settings.gradle'
        
        * What went wrong:
        Could not compile settings file 'D:\Projects\EclipseProjects\jpf-core\settings.gradle'.
        > startup failed:
          General error during semantic analysis: Unsupported class file major version 61
        
          java.lang.IllegalArgumentException: Unsupported class file major version 61

Running the gradlew.bat file also produces the same error.

Can anyone guide on the issue or help with the installation process?

**Comment by franck-van-breugel** [comment]
Use Java 8.

**Comment by MariaSalim** [comment]
Thank you @franck-van-breugel, it worked!
