### ISSUE TITLE
How about migrating the project from java to kotlin.

### ISSUE THREAD

**Issue by adicoder95** [javapathfinder/jpf-core#333]
Kotlin based apps can perform better, thus making the app smoother.
I am a Kotlin developer and I would love to contribute in this project.

**Comment by cyrille-artho** [comment]
The JPF codebase requires a close interaction with the data structures of the underlying host JVM and its native methods. I do not see how using Kotlin would help in the code of jpf-core itself.
However, we could use help with adapting Kotlin libraries to JPF. I have a student who is working on this and will probably soon make a first contribution. There is more work to be done in that area for sure.
