### ISSUE TITLE
PreciseRaceDetector raises false alarms in case of array fields

### ISSUE THREAD

**Issue by quadhier** [javapathfinder/jpf-core#344]
Hi, `jpf` is a great tool and I use it for bug hunting in Java programs. I have come up with an unexpected alarm when I used it to do race detection. So I did some input reduction and bug diagnosis work. Hope it will help.

## A Description of the Problem
JPF has a listener for data race detection (`gov.nasa.jpf.listener.PreciseRaceDetector`). It raises false alarms in the case of two threads writing to **different array fields** of one class. Though I only run `jpf` of branch `java-10-gradle` under `openjdk-11u`, I think this problem is not platform-dependent and may also exist in other branches. I have included detailed information below.

## System Information
```bash
$ git branch
* java-10-gradle
$ uname -op
x86_64 GNU/Linux
$ java -version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

## Steps to Reproduce
1. Create a file of the path `jpf-core/src/examples/ArrayNoRace.java` with the following content.
```java
/*  L1 */ class ArrayNoRace {
/*  L2 */
/*  L3 */   static int[] arr1 = new int[2];
/*  L4 */   static int[] arr2 = new int[2];
/*  L5 */
/*  L6 */   static void writeFirst(int[] arr) {
/*  L7 */     arr[0] = 0;
/*  L8 */   }
/*  L9 */
/* L10 */   public static void main(String[] args) {
/* L11 */     Thread t1 = new Thread() {
/* L12 */       @Override
/* L13 */       public void run() {
/* L14 */         writeFirst(arr1);
/* L15 */       }
/* L16 */     };
/* L17 */
/* L18 */     Thread t2 = new Thread() {
/* L19 */       @Override
/* L20 */       public void run() {
/* L21 */         writeFirst(arr2);
/* L22 */       }
/* L23 */     };
/* L24 */
/* L25 */     t1.start();
/* L26 */     t2.start();
/* L27 */   }
/* L28 */ }
```

2. Add the following line to `jpf-core/jpf.properties` (Use `PreciseRaceDetector` during the following `jpf` run)
```
listener=gov.nasa.jpf.listener.PreciseRaceDetector
```

3. build the `jpf-core` project
```bash
$ ./gradlew clean buildJars
```

4. Run the race detector on `ArrayNoRace`
```bash
$ cd ./bin
$ ./jpf ArrayNoRace
```

### Expected Ouput
```bash
...
====================================================== results
no errors detected

====================================================== statistics
...
```

### Actual Output
```
...
====================================================== error 1
gov.nasa.jpf.listener.PreciseRaceDetector
race for array element [I@1e2[0]
  Thread-1 at ArrayNoRace.writeFirst(ArrayNoRace.java:7)
                "/*  L7 */     arr[0] = 0;"  WRITE: iastore
  Thread-2 at ArrayNoRace.writeFirst(ArrayNoRace.java:7)
                "/*  L7 */     arr[0] = 0;"  WRITE: iastore


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
        at java.lang.Thread.start(Thread.java)
        at ArrayNoRace.main(ArrayNoRace.java:26)

thread ArrayNoRace$1:{id:1,name:Thread-1,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
        at ArrayNoRace.writeFirst(ArrayNoRace.java:7)
        at ArrayNoRace$1.run(ArrayNoRace.java:14)

thread ArrayNoRace$2:{id:2,name:Thread-2,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
        at ArrayNoRace.writeFirst(ArrayNoRace.java:7)
        at ArrayNoRace$2.run(ArrayNoRace.java:21)


====================================================== results
error #1: gov.nasa.jpf.listener.PreciseRaceDetector "race for array element [I@1e2[0]   Thread-1 at Arr..."

====================================================== statistics
...
```

## Bug Diagnosis
I found that `PreciseRaceDetector` uses `peekArrayElementInfo()` to get array object reference.

https://github.com/javapathfinder/jpf-core/blob/a8160543fecaee799587c955c429aa7f068a410a/src/main/gov/nasa/jpf/listener/PreciseRaceDetector.java#L237-L245

According to the following comments, this array object reference **need to be the one on the operand stack**.

https://github.com/javapathfinder/jpf-core/blob/a8160543fecaee799587c955c429aa7f068a410a/src/main/gov/nasa/jpf/listener/PreciseRaceDetector.java#L259-L275

However, in `peekArrayElementInfo()`'s implementation, it invokes `getArrayRef()`, which **only makes sense in `executeInstruction()` or `instructionExecuted()`** listeners, as indicated by the following comments in the code. But `PreciseRaceDetector` is not this type of listener (it checks race in `choiceGeneratorSet()`). Therefore, `getArrayRef()` returns a cached array object ref instead of the one on the operand stack, which is not what `peekArrayElementInfo()` wants. And finally `PreciseRaceDetector` also **gets an cached array object ref that it doesn't expect**. Finally it raises a false alarm.

https://github.com/javapathfinder/jpf-core/blob/a8160543fecaee799587c955c429aa7f068a410a/src/main/gov/nasa/jpf/jvm/bytecode/JVMArrayElementInstruction.java#L60-L70

## A Tentative Fix
Maybe we should use `peekArrayRef()` instead of `getArrayRef()` in the implementation of `peekArrayElementInfo()`.
```diff
--- a/src/main/gov/nasa/jpf/jvm/bytecode/JVMArrayElementInstruction.java
+++ b/src/main/gov/nasa/jpf/jvm/bytecode/JVMArrayElementInstruction.java
@@ -88,7 +88,7 @@ public abstract class JVMArrayElementInstruction extends  ArrayElementInstructio

   @Override
   public ElementInfo peekArrayElementInfo (ThreadInfo ti){
-    int aref = getArrayRef(ti);
+    int aref = peekArrayRef(ti);
     return ti.getElementInfo(aref);
   }
```

**Comment by cyrille-artho** [comment]
Thanks for this in-depth analysis!
Does your patch work if the same array reference is passed to each thread, in which case a true positive data race should still be reported?
I think it would be great to have this fix together with two tests, the one example above, and a modified version that uses the same array. The first test should report no errors, the second one a data race.

**Comment by quadhier** [comment]
Hi, @cyrille-artho 
Thanks for your suggestions! 😎
I tested it and the patch works for both cases you mentioned.
I submitted a PR for the fix with four unit tests. Would be super grateful if you could take another look and review it for me. Thanks a bunch! 🙌

**Comment by cyrille-artho** [comment]
Thank you, I have merged the patch and will close this bug report.
We still have some unit tests that fail, so I had to ignore the failure in the CI.
I think this patch is also applicable to main, for which CI is supposed to succeed.

**Comment by quadhier** [comment]
Yep!
I'd like to patch `main` branch as well. I'll submit another patch later. 😎
Thanks for your patience! 😄
