### ISSUE TITLE
Wiki needs update

### ISSUE THREAD

**Issue by HawkItzme** [javapathfinder/jpf-core#346]
As the JPF team is accepted and the organization is visible in the list of GSoc 2023 selected orgs. So the wiki needs few typo changes

**Comment by Abhishekverma2002** [comment]
A pull request has been made from my side to the wiki-sync repo. Do check it out and merge it. 
@HawkItzme

**Comment by HawkItzme** [comment]
Bro, I am not the project admin , I am also a contributor.

**Comment by Abhishekverma2002** [comment]
Who is the maintainer? I have pull requested about this issue a while back and no one is responding to that request.

**Comment by HawkItzme** [comment]
No idea bro
