### ISSUE TITLE
Check if the classpath exception is present in all model class files we use from OpenJDK 11

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#370]
We have a few model class files from OpenJDK, which are likely subject to the "classpath exception" in the license. We need a list of all files to see if they are all covered by this and if they all contain the text with the exemption in our simplified version of it.

**Comment by cyrille-artho** [comment]
The new licensing scheme from JDK 11 onward seems to permit this; now, we need to find out whether GitHub actions support Oracle's JDK.

**Comment by cyrille-artho** [comment]
Varadraj has checked this; only three files are affected:
    Calendar.java
    SecuritySupport.java
    DateFormat.java
We now have to add the extra license terms and a copy of the GPL 2.0 license at the top level (with some information that only three files are affected by it and under the classpath exception).

**Comment by cyrille-artho** [comment]
Unfortunately, we cannot simply change the license, but perhaps the author agrees to a change if we ask them. Having fewer GPL-licensed files would help us manage them.

**Comment by varad64** [comment]
Hello @cyrille-artho and @pparizek, with the merging of PR #413, all files now use the `Apache License v2.0` and no files are now subject to the Classpath exception via GPL. This issue can now be closed.

Thanks!
