### ISSUE TITLE
Migration to Java 11

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#416]
The default `master` branch now supports Java 11.
Java 8 support is on branch `java-8`.
Please update your local repos if you have cloned `jpf-core` earlier. We will soon update the documentation.

```
git branch -m java-10-gradle master
git fetch origin
git branch -u origin/master master
git remote set-head origin -a
```

**Comment by Tejasker** [comment]
Hi @cyrille-artho, is there anything that needs changes in documentation as mentioned above?
or else the changes are done as needed, if not I can make changes accordingly.

**Comment by cyrille-artho** [comment]
No, the documentation is up to date. We created this issue to help with transitioning from a cloned repository from before Aug 28 (2023), and as almost four months have passed now, we can close this issue.
