### ISSUE TITLE
Build Error occurring when I have the correct version of Java installed?

### ISSUE THREAD

**Issue by StarlightRT** [javapathfinder/jpf-core#426]
I am trying to build the JPF with the master branch. I have the correct version of Java yet am getting the following error. I have reinstalled Java 11 many times. What can I do to solve this?

![Screenshot 2023-11-28 203459](https://github.com/javapathfinder/jpf-core/assets/32223170/65e5ab59-6c00-4764-af41-8f07f450210d)

Thanks

Edit: I have updated to Java 11.21 and that is also not working correctly.

![image](https://github.com/javapathfinder/jpf-core/assets/32223170/df043c86-47ce-4fbb-952a-cdab59ec1d20)

**Comment by ghost-cai** [comment]
I used the openjdk11 but still have this error.
![image](https://github.com/javapathfinder/jpf-core/assets/73644390/35e0264b-ebbf-4b4f-b265-ca61e7785b59)

**Comment by cyrille-artho** [comment]
You need OpenJDK version 11, but probably a newer version. I use:
```
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9)
OpenJDK 64-Bit Server VM (build 11.0.21+9, mixed mode)
```

**Comment by ghost-cai** [comment]
I hava an another question. Can jpf-core used to a whole jar package? Hope your answer.

**Comment by cyrille-artho** [comment]
The classes you want to analyze simply have to be accessible to JPF, either as class files or in a JAR file. As long as you set the classpath options correctly, JPF can find them.

**Comment by ghost-cai** [comment]
But don't have an example in the examples.I hope the officials can write an example about analyzeing a whole jar package. We can easier and more detailde to know how to use the jpf-core.

**Comment by cyrille-artho** [comment]
Yes, this would be helpful. I think a separate stand-alone mini project that builds one or two files from scratch and then runs them in JPF could illustrate how JPF is used from a new project.
Such a project could be in its own repository, as to reflect how a "real" project would integrate using JPF.
