### ISSUE TITLE
The wrapper.jar checksum is not consistent with the gradle version.

### ISSUE THREAD

**Issue by HappyHacker123** [javapathfinder/jpf-core#432]
# Problem Description
Currently jpf-core is using gradle 8.4 and current gradle-wrapper.jar checksum is 91941f522fbfd4431cf57e445fc3d5200c85f957bda2de5251353cf11174f4b5. However, as can be seen from https://gradle.org/release-checksums/, the expected checksum of wrapper.jar 8.4 should be 0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15. The inconsistency means that the wrapper.jar is stale and should be updated.

# Possible Solution 
As mentioned in gradle official document https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper, you will need to run the wrapper task a second time to make sure the wrapper.jar is updated. You can run the below command in the root project. Automatically the wrapper scripts will be generated by gradle.

```
bash gradlew wrapper
```

**Comment by HappyHacker123** [comment]
> Hi, Thank you very much for pointing this out. I have run the `./gradlew wrapper` task locally, but now the checksum for `gradle-wrapper.jar` is 9a441e5080ee4b41eea415c020af18f4d7852ee2. This is different than before but still not the expected checksum. Any ideas why this may be the case?

Thanks for your reply :). I think maybe you run 'shasum', it calculates the  SHA1 checksum of the jar. The checksum released by gradle is SHA256 checksum. If you run 'sha256sum', you will get the expected checksum :).

**Comment by cyrille-artho** [comment]
Thanks, that was the reason. I've pushed a commit to update the wrapper.
We don't have a process to do this regularly, as we typically only update the wrapper for a new Gradle release. But we can update it periodically if there is a patch that makes it more robust.
