### ISSUE TITLE
Java 17 support: CI configuration, identification of key issues

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#442]
Java 17 is the next long-term support release after Java 11. Thanks to @eklaDFF's patch, we can now compile JPF under OpenJDK 17.
About 3/4 of all unit tests fail, though: `1002 tests completed, 759 failed`

We also need to configure CI so it uses Java 17 and can auto-test any future PRs.

Among the many failing tests, we first have to get an overview of key issues that make the tests fail. It is likely that a few issues are responsible for dozens or hundreds of failures.

Once we get a majority of tests to pass, we also want to add a few additional tests to cover new features that were added with Java 17.

**Comment by eklaDFF** [comment]
Hi, can you suggest some direction to look.
Currently I have seen that most of the errors are due to a new method added in `Unsafe` class. That method calls an `native method` which is to be implemented in native implementations.

<img width="1280" alt="Screenshot 2024-04-15 at 7 44 24 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/8b0f0a81-a623-4736-a152-0f66a26a4be5">
<img width="1280" alt="Screenshot 2024-04-15 at 7 45 16 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/8584798e-beda-4806-a5ac-34c77a36f68e">

**Comment by eklaDFF** [comment]
> Hi, can you suggest some direction to look. Currently I have seen that most of the errors are due to a new method added in `Unsafe` class. That method calls an `native method` which is to be implemented in native implementations.
> 
> <img alt="Screenshot 2024-04-15 at 7 44 24 PM" width="1280" src="https://private-user-images.githubusercontent.com/78310039/322514137-8b0f0a81-a623-4736-a152-0f66a26a4be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTEwOTYsIm5iZiI6MTcxMzE5MDc5NiwicGF0aCI6Ii83ODMxMDAzOS8zMjI1MTQxMzctOGIwZjBhODEtYTYyMy00NzM2LWExNTItMGY2NmEyNmE0YmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNGM0MDk2N2QyZmQ5ZDM5OGViNmJkOTAzYWQ4OWQ4ZGFjODIyOTYxZTI2MGJmODE0MWFiMDhlNGM5YmY5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uELdR6vjNigDdAYzPEZZL9jFlOi9MD4Apqr4Om6_Q3M"> <img alt="Screenshot 2024-04-15 at 7 45 16 PM" width="1280" src="https://private-user-images.githubusercontent.com/78310039/322514183-8584798e-beda-4806-a5ac-34c77a36f68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTEwOTYsIm5iZiI6MTcxMzE5MDc5NiwicGF0aCI6Ii83ODMxMDAzOS8zMjI1MTQxODMtODU4NDc5OGUtYmVkYS00ODA2LWE1YWMtMzRjNzdhMzZmNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZGNkNWIyYWQyYWU1NGE3ZDkyN2VlNDUwYmZjNDY4ZGYwM2Q1MWJlY2Q1YjVlZWFiMGZjMjc1NjA0MDllMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bnWkvmM3fExIDvgUcMJxrVYjh8X4GHLaDCUDIUM-oUs">

<img width="1099" alt="Screenshot 2024-04-12 at 11 58 40 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/489dc5ce-f14b-47a4-ac68-0bbaa3cec323">
<img width="1099" alt="Screenshot 2024-04-12 at 11 59 09 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/ca87a7ab-7986-472a-967a-90a55229e662">

**Comment by cyrille-artho** [comment]
I think that setting up CI is best done early (I thought it was set up, but the CI builds have not been triggered for some reason).
As far as the test failures go, the changes in the package names that you pointed out are probably the best thing to take care of first. You can try to find the right text string or regular expression to run a global search/replace. By doing so, you will probably fix many issues at a time.
Once you have CI working (or if you get stuck and cannot find out why it doesn't run), I recommend the following:

0. Ensure the git repo is "clean" (no uncommitted or unpushed changes).
1. Identify a string to search/replace, or a regex.
2. Run `find . -name '*.java' | xargs sed -i bak -e 's/search_regex/replace_regex/g'`.
3. Try `./gradlew clean test` to see if the test outcome improves.
4. git diff; check if all the changes really make sense.
5. If a change is part of a bigger task, create a separate issue for this.
6. If everything looks good, create a pull request against `java-17`, mentioning either this issue or a new (smaller) issue.

**Comment by eklaDFF** [comment]
Hi @cyrille-artho , are you pointing to the `jdk.internal.misc` and `jdk.internal.access`, and to ensure that every package is importing it correctly ?

Please explain in more detail.

**Comment by eklaDFF** [comment]
Should I read the documentation first to get overall picture to handle above errors ?

**Comment by cyrille-artho** [comment]
Regarding the package names, those were the package names in Java 11, but Oracle has shuffled around some packages, so they have different names in Java 17. I think the best way to fix some of these issues is to look up (for a given class in one given failing test) what the new package/class name is in Java 17. You then do one global search/replace in all the import statements in the entire code base. This will hopefully reduce the number of failing tests or at least not increase them.

Getting an overall picture of all errors likely involves substantial work, as different types of problems manifest themselves differently. Our end goal is to fix all errors, so for now, there is no (long-term) benefit in a comprehensive analysis and then prioritizing particular errors.

I think the best approach is as follows:

1. You look at one or a few failing tests until you find one where it looks obvious to you how it can be fixed.
2. You attempt a fix.
3. If you are successful and the number of failing tests does not increase, you can commit the change and make a PR against `java-17`. (Even if your fix does not make the test pass, it will make the test run further until failure.)
4. If the test requires more work to pass and you know how to proceed, you can continue with the next part to fix there.
5. If you get stuck and do not know how to proceed, choose a different (easier) target by going back to step 1 (skipping tests where you are not sure what to do).

It is possible that some tests fail due to compound problems, which are hard to analyze. Therefore, if you fix the "easy" problems first, even the hard problems may become easier to figure out.

**Comment by cyrille-artho** [comment]
> Should I read the documentation first to get overall picture to handle above errors ?

Yes, for each problem (and incompatible API), you can often find documentation of what changes from Java 11 to Java 17 and how you adapt the code. Try to handle one type of problem at a time, and if one type of problem seems very hard, skip it and move to the next one.

**Comment by cyrille-artho** [comment]
It may be possible to map this to the right method in `src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java`, but I'm not 100 % sure if `getObjectVolatile__Ljava_lang_Object_2J__Ljava_lang_Object_2` is the right one. In any case, because JPF is not concurrent in itself, the "volatile" variants of the methods map to the regular ones.

You probably first have to declare a native method in the "model class" in `src/classes/modules/java.base/jdk/internal/misc/Unsafe.java` and then a counterpart in the native peer in ``src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java`.

See the wiki, https://github.com/javapathfinder/jpf-core/wiki/Model-Java-Interface, for more information.

**Comment by eklaDFF** [comment]
Should I map to this `getBoolean__Ljava_lang_Object_2J__Z` method of `src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java` ?

**Comment by cyrille-artho** [comment]
`getBoolean` returns  either `true` or `false`, not a reference; so this is not the right method for `compareAndSetReference`. If there is no corresponding native peer in jpf-core as of now, you have to write a new method. You can look at the JPF source and the OpenJDK source to see what the method should do and how it could be written.

**Comment by eklaDFF** [comment]
I tried but was unable to get the directory where I could find out the implementation of `compareAndSetReference`. Please help !

<img width="1103" alt="Screenshot 2024-04-22 at 6 33 54 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/4b5a4626-4bd4-4da8-aa63-f0a917add7f1">

{Possible Solution}
One thing I have noticed that there is one method named `putObject__Ljava_lang_Object_2JLjava_lang_Object_2__V` which is called by method `compareAndSetObject__Ljava_lang_Object_2JLjava_lang_Object_2Ljava_lang_Object_2__Z`. And, we are in need of a method which can be used for reference or we can say Object also. Do you you think that we should try this method.

<img width="1132" alt="Screenshot 2024-04-22 at 11 38 31 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/370da456-1034-494b-95bc-fdead98ff601">

**Comment by cyrille-artho** [comment]
It's possible that this was just a renaming from `...Object` to `...Reference`. If you compare the interfaces of `Unsafe` in Java 11 and Java 17, you can probably confirm if that's the case.

**Comment by eklaDFF** [comment]
Screenshot from OpenJDK 11
<img width="1073" alt="Screenshot 2024-04-24 at 7 24 35 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/a386d741-c328-4977-8f7b-490d3b155e6c">

In OpenJDK 11, `comareAndSetObject(....)` is implemented as `native`.

Screenshot from OpenJDK 17
<img width="1176" alt="Screenshot 2024-04-24 at 7 25 05 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/87445782-b1a1-4964-9b9f-7a284f4f6959">

In OpenJDK 17, `comareAndSetObject(....)` is implemented as `non native` but it is calling `native` method `comapreAndSetRefrence(...)`.

Overall, `comareAndSetObject(...)` has been turned to a `non-native` method and it is calling the newly introduced `native` method `comapreAndSetRefrence(...)`.

First Solution :  We will declare `comapreAndSetRefrence(...)` as `non native` method in model `Unsafe` class. And then call `comareAndSetObject(....)` from it. This way, we can avoid any changes in peers.

Second Solution : We will declare `comapreAndSetRefrence(...)` as `native` method in model `Unsafe` class (Same as it is declared in OpenJDK 17). And then implement the corresponding method in peers where it will call peer implementation of `comareAndSetObject(...)`.

Which solution would be best suited ?

**Comment by cyrille-artho** [comment]
Thanks, now I understand. I think `...setReference` is an extra layer to handle the native side to `...setObject`. Because `...setReference` is sometimes called directly, we need to have that method as well.
We want to have the same non-native/native declarations as in OpenJDK 17. We already have a working native peer for `...setObject`, but that one will now become `...setReference`, and `setObject` will be only a model class calling native `...setReference` internally.

**Comment by cyrille-artho** [comment]
In principle, it's always best to mirror the declarations of OpenJDK as far as possible, as this likely avoids incompatibilities down the line.

**Comment by eklaDFF** [comment]
Hi, I did the same as you per your guide.

We have now 334 failed tests

<img width="1176" alt="Screenshot 2024-04-25 at 1 36 31 AM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/1109409c-e0cc-4c6e-854e-53edf339a048">

Analyzing the failed tests, we found as below (in most cases or say in larger order)

```
running jpf with args:
JavaPathfinder core system v8.0 (rev 595cb07e83a621f2b4d90eaf34cc99c41f6f82e0) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.java.io.FileTest.runTestMethod()

====================================================== search started: 25/04/24, 1:08 am
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;

====================================================== results
no errors detected

====================================================== search finished: 25/04/24, 1:08 am
  running jpf with args:
JavaPathfinder core system v8.0 (rev 595cb07e83a621f2b4d90eaf34cc99c41f6f82e0) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.java.io.FileTest.runTestMethod()

====================================================== search started: 25/04/24, 1:08 am
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;

====================================================== results
no errors detected

====================================================== search finished: 25/04/24, 1:08 am
  running jpf with args:
JavaPathfinder core system v8.0 (rev 595cb07e83a621f2b4d90eaf34cc99c41f6f82e0) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.java.io.FileTest.runTestMethod()

====================================================== search started: 25/04/24, 1:08 am
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodError: java.lang.String.getBytes([BIIBI)V
	at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1720)
	at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1724)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:583)
	at java.lang.StringBuilder.append(StringBuilder.java:179)
	at java.lang.StringBuilder.append(StringBuilder.java:173)
	at java.lang.String.generateStringByConcatenatingArgs(String.java:1078)
	at java.io.File.<init>(File.java:59)
	at gov.nasa.jpf.test.java.io.FileTest.testGetCanonical(FileTest.java:81)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.NoSuchMethodError: java.lang.String.getB..."

====================================================== search finished: 25/04/24, 1:08 am
```

From above snapshot, we can see that throws `NoSuchMethodError` for `java.lang.String.getBytes( )`. But in source code of OpenJDK 17, `java.lang.String.getBytes( )` is defined.

**Comment by cyrille-artho** [comment]
Thanks! Please make a pull request with the fix for `Unsafe`, and we can look at `String` afterward.
There is already some support for `getBytes` in JPF's native peer, so I hope that this specialized method can be supported based on existing code.

**Comment by eklaDFF** [comment]
PR #444

**Comment by cyrille-artho** [comment]
The build still fails on the CI setup, although it works locally:
```
Execution failed for task ':compileAnnotationsJava'.
> error: invalid source release: 17
```
I have tried to update the CI configuration, but could not get it to work yet.

**Comment by eklaDFF** [comment]
Moment ago fired the command `./gradlew check` and the result was same (334 failures) locally on my mac. 

While on GitHub, is it building on JDK 11 ?
<img width="1440" alt="Screenshot 2024-04-25 at 7 45 47 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/f3535d68-105a-4607-a19e-49534e75716d">

If not, what should I do next ?

**Comment by cyrille-artho** [comment]
I can also reproduce your test result locally. So if you isolate the new changes in the PR, I will merge it.
As for the CI build, we can just keep troubleshooting. The distribution `adopt` of OpenJDK is supposed to work, but maybe one of many other distributions works better. I can see from the output above that JDK 11 is active, so we have to switch the right setting to JDK 17.

**Comment by cyrille-artho** [comment]
No, that goes too far, as you have to first update your branch every time you want to make a PR.
You can instead pull from the original repo (onto your branch) every time before making a new feature.
Then, instead of working on branch `java-17`, best practice is to start a new temporary branch (aka "feature branch) from the recently updated `java-17` and use this for your PR. The PR is then from your feature branch in your repo to `java-17` on the main repo.
After the PR is merged, you delete that feature branch, update `java-17` on your repo, and start a new feature branch.

**Comment by eklaDFF** [comment]
I created a new branch named with `java-17`(locally) and pulled and override code from `jpf-core:java-17`, and this resulted in getting the exact copy of `jpf-core:java-17`. 
And then created a new branch named `UnsafeFixingNewBranch` to just copy the current status `jpf-core:java-17` so that to do the new changes. Now this (`UnsafeFixingNewBranch`) was copy of `java-17` (local) branch. Now to get the changes made to fix `Unsafe` class I rebase the current branch with `master` (in `master` branch I did all the fixing of `Unsafe` class). So currently my `UnsafeFixingNewBranch` contains all the fixing of `Unsafe` class. Against this branch I created a PR.

But now there is showing 14 commits including yours.

Where did I went wrong ? (I rebased the `UnsafeFixingNewBranch` from `master` to just append the `Unsafe` class fixing commit)

**Comment by eklaDFF** [comment]
#447 
Created the PR.

**Comment by cyrille-artho** [comment]
Yes, this patch has only the new changes, so I merged it. CI is now working, too!

**Comment by cyrille-artho** [comment]
Let's continue on a separate issue, as the main issues (CI config) are taken care of, and I think it's easier to follow an issue if we start again with a new one.

**Comment by eklaDFF** [comment]
Should I have to open a new issue, or you have opened ?
