### ISSUE TITLE
java.lang.NoSuchMethodError: java.lang.String.getBytes([BIIBI)

### ISSUE THREAD

**Issue by eklaDFF** [javapathfinder/jpf-core#448]
Tests cases throws an error `java.lang.NoSuchMethodError: java.lang.String.getBytes([BIIBI)` for `jpf-core` built on `OpenJDK 17`.

**Comment by eklaDFF** [comment]
Hi @cyrille-artho,
`java.lang.NoSuchMethodError: java.lang.String.getBytes([BIIBI)` is defined in OpenJDK 17.

<img width="1162" alt="Screenshot 2024-04-27 at 7 41 55 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/030574fd-7fb4-4067-8a4e-6999a2877f2f">

**Comment by cyrille-artho** [comment]
This one comes from an innocuous-looking string concatenation, but it is perhaps not as simple as it looks.
This variant of `getBytes` is not part of the public API, so it is an internal method. If we can find out what is the expected functionality of `getBytes`, we can probably support it in JPF as well.
Another approach would be to create a model class for `StringBuilder`, but I'd rather avoid that, as we didn't need it so far. Even if this variant of `getBytes` may be a bit complicated, it's still easier to support only one more method than an entire new class.

**Comment by eklaDFF** [comment]
In our model `String` class, this is how `getBytes` defined.

<img width="1440" alt="Screenshot 2024-04-28 at 6 54 46 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/7ff3540b-1718-4223-9aa9-4a2d5ac8056e">

one of the above method is defined as `native` whose implementation is defined as in the native peer

<img width="1440" alt="Screenshot 2024-04-28 at 6 53 49 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/00da9634-038c-47a1-ad44-53582551e6ef">

and now our `getBytes(I I []B I)` which is used by `AbstractStringBuilder` class is defined as below

<img width="1440" alt="Screenshot 2024-04-28 at 6 53 30 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/d3f13f6a-ae35-4ce6-b8db-9407bdd8a8cb">

In the new `getBytes([]B I I B I)`, one parameter is being introduced named with `byte coder`. 

Now let's see implementation of the `getByte(I I []B I)` in `OpenJDK 11`

<img width="1440" alt="Screenshot 2024-04-28 at 7 03 11 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/b8eeadc6-1e29-4257-8920-37612f8801ee">



Possible Solution :

Seeing the implementation in OpenJDK 11 and `native-peer`, we are ignoring the `coder` type. 
So can we add that parameter `byte code` and later ignoring them in the body of `getByte(I I []B I)` ?

**Comment by cyrille-artho** [comment]
Thanks for looking into this. Yes, I agree that ignoring `coder` is probably the best approach.

A side note:
I'm surprised that the method even get an update with Java 17, as it is known to have potential problems with correct encoding (and hence it's deprecated).
As the new `getBytes` an internally used method, it will likely suffice to have an implementation that passes our tests. JPF (at least `jpf-core`) is usually not used to analyze complex strings. If someone uses SPF (a JPF extension), which covers some of the use cases of string analysis, then they will use an entirely different engine to handle symbolic string values.

**Comment by eklaDFF** [comment]
While implementation I found out below : 

here is the native method from our model class
```
@Deprecated
native public void getBytes(int srcBegin, int srcEnd, byte dst[], int dstBegin);
```
and here is the implementation in `native peer`
 ```
@MJI
public void getBytes__II_3BI__V (MJIEnv env, int objRef, int srcBegin, int srcEnd, int dstRef, int dstBegin) {
    String obj = env.getStringObject(objRef);
    byte[] dst = env.getByteArrayObject(dstRef);
    obj.getBytes(srcBegin, srcEnd, dst, dstBegin);
  }
```
in above code we can see that `obj.getBytes(I,I,[ ]B,I)` is being called. And the `getBytes()` method with such parameters are still in OpenJDK 17 with tag of `deprecation`

<img width="1440" alt="Screenshot 2024-04-29 at 9 01 38 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/e2ee93d5-1bcb-4ce8-8eaf-f467e6f6bef1">

and also (our new `getBytes` with slightly different params)

<img width="1440" alt="Screenshot 2024-04-28 at 6 53 30 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/e85cd418-6823-45f5-8229-3d08aa09d5f5">


So, now what approach should we follow

Approach 1 :  We should write new `overloaded` method for our new `getBytes()` and call the older `getBytes()` to avoid any changes in `native peer`. This will use `deprecated` `getBytes()`. Here we will ignore the `coder`.

Approach 2 : We should write parallel native method for new `getBytes()` and also implement then in `native peer` which will eventually call the new `getBytes` of OpenJDK 17. In this case you will have to guide me to write new implementation of `getBytes()` in native peer.

**Comment by cyrille-artho** [comment]
We probably have not tested the corner cases very well; I am not sure if we cover `getBytes` for `LATIN` strings.
So it's probably best to implement a new `getBytes` for the case with the additional `coder` argument, which we can then pass to the JPF native peer, which then uses the Java 17 `getBytes` that also has a `coder` argument. This will cover the unusual case in the `else` statement in the screenshot above.

For native methods, check the "MJI" page on the wiki: https://github.com/javapathfinder/jpf-core/wiki/Model-Java-Interface

If something is not clear, please let me know, and we can improve the description there.

We now also have the recent paper on JPF available on open access: https://link.springer.com/content/pdf/10.1007/978-3-031-57249-4_1

**Comment by eklaDFF** [comment]
Hi, I was able to write the implementation for new getBytes(). But we cannot call that newer getBytes() because it is internal method in OpenJDK 17.

<img width="983" alt="Screenshot 2024-05-02 at 11 34 43 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/27262d5a-24ae-4780-89be-f841c52f6515">

<img width="757" alt="Screenshot 2024-05-02 at 11 40 14 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/57182e47-d573-4f12-ade4-2b04694d6e33">


Either we have to use approach of ignoring coder or we have to create our own getByte in String model class.

Please let me know if there is any better solution ?

**Comment by cyrille-artho** [comment]
Thank you, that's right.
What happens if you try option 1 above, simply ignoring the coder?
If this causes issues with some tests or uses of JPF, we could always construct a new `String` at the JPF-native level (in the `@MJI` code) and call `getBytes` there, which will then internally use the right method with the internal `coder` reference.
Because string encodings are not a big use case in `jpf-core`, perhaps the simple pragmatic approach that works in usual cases is fine.

**Comment by eklaDFF** [comment]
Approach 1 : Ignoring the coder
Created an `overloaded` method for `getBytes()` like below.

<img width="1285" alt="Screenshot 2024-05-03 at 2 48 14 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/f347bcf0-4b9a-4528-8e07-a1202ee73296">


Approach 2 : [ Purpose : To check the use of `getBytes()` if we implement at the JPF-native level ]
I just implemented the `getBytes()` in our model class like below.

<img width="1285" alt="Screenshot 2024-05-03 at 2 33 58 PM" src="https://github.com/javapathfinder/jpf-core/assets/78310039/1727b0fa-0c0c-4eb6-bb30-8b253c51c398">



**In both approach there is 38 failed test.**

**Comment by cyrille-artho** [comment]
I think the first approach is better then, because OpenJDK source code is under a different license (GPL) than JPF's code (Apache 2.0). In this case, the copied code is very short, but we want to avoid copying code nonetheless, to avoid having a mix of very different licenses.

**Comment by eklaDFF** [comment]
Here is fresh new major source of errors (38 failed test).

```
running jpf with args:
JavaPathfinder core system v8.0 (rev fd73ee185637c825bb49c944bdc90f5e165c44c2) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.java.concurrent.ConcurrentSkipListMapTest.runTestMethod()

====================================================== search started: 03/05/24, 4:24 pm
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;
[WARNING] orphan NativePeer method: jdk.internal.reflect.Reflection.getCallerClass(I)Ljava/lang/Class;

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.CDS.isDumpingClassList0
	at jdk.internal.misc.CDS.isDumpingClassList0(no peer)
	at jdk.internal.misc.CDS.<clinit>(CDS.java:49)
	at java.util.ImmutableCollections.<clinit>(ImmutableCollections.java:80)
	at java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:786)
	at java.util.Set.of(Set.java:470)
	at jdk.internal.reflect.Reflection.<clinit>(Reflection.java:49)
	at java.lang.invoke.MethodHandles$Lookup.<clinit>(MethodHandles.java:1433)
	at java.lang.invoke.MethodHandles.lookup(MethodHandles.java:116)
	at java.util.concurrent.ConcurrentSkipListMap.<clinit>(ConcurrentSkipListMap.java:3407)
	at gov.nasa.jpf.test.java.concurrent.ConcurrentSkipListMapTest.testFunctionality(ConcurrentSkipListMapTest.java:35)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  owned locks:java.lang.Class@227,java.lang.Class@24c,java.lang.Class@26c,java.lang.Class@274,java.lang.Class@277
  call stack:
	at jdk.internal.misc.CDS.<clinit>(CDS.java:49)
	at java.util.ImmutableCollections.<clinit>(ImmutableCollections.java:80)
	at java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:786)
	at java.util.Set.of(Set.java:470)
	at jdk.internal.reflect.Reflection.<clinit>(Reflection.java:49)
	at java.lang.invoke.MethodHandles$Lookup.<clinit>(MethodHandles.java:1433)
	at java.lang.invoke.MethodHandles.lookup(MethodHandles.java:116)
	at java.util.concurrent.ConcurrentSkipListMap.<clinit>(ConcurrentSkipListMap.java:3407)
	at gov.nasa.jpf.test.java.concurrent.ConcurrentSkipListMapTest.testFunctionality(ConcurrentSkipListMapTest.java:35)
	at java.lang.reflect.Method.invoke(Method.java)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.UnsatisfiedLinkError: cannot find native..."

====================================================== search finished: 03/05/24, 4:24 pm
```

**Comment by cyrille-artho** [comment]
Great, please make a PR with the `String` fix, and let's move to a new issue with the next problem.
The next issue is again complex, as there are several classes for which we do not have model classes right now, but we probably have to add at least one model class to support this case.

**Comment by eklaDFF** [comment]
Created #449
