### ISSUE TITLE
Add Java Plugin to the Gradle build

### ISSUE THREAD

**Issue by jeandersonbc** [javapathfinder/jpf-core#46]
The Gradle Java plugin already has common build tasks for Java/JVM project such as generating jars, compiling classes, and so on. Also, it is configurable to support jpf project layout.

More info: https://docs.gradle.org/current/userguide/tutorial_java_projects.html

**Comment by jeandersonbc** [comment]
I added a Gradle script for compilation and test execution. I compared the number of tests executed and both (Gradle and Ant) are consistent.

However, only 75% of tests are passing on the Gradle build.
I sampled some errors to investigate, and I noticed that some of them are due to hardcoded paths on tests, like here in the `MethodInfoTest` class:

```java
  @Test
  public void testMethodArgs() {
    File file = new File("build/tests/gov/nasa/jpf/jvm/MethodInfoTest$MyClass.class");
```
The build directory generated by Gradle has a different layout.
I need to confirm all cases first to be 100% sure but I believe that all errors are similar to this.
Changing those hardcoded paths doesn't seem to help the problem at all.
I need to figure a way to preserve the generated directories.

**Comment by jeandersonbc** [comment]
I made some marginal improvement by making the generated directory three similar to the ant-generated build directories. Now, 78% of tests.

This means that only 3% depends on a compiled class file as a test resource.
All the remaining 22% failed tests depend on a jar file as a test resource.

I must work on this to have 100% of tests passing.

I wonder if jar dependent tests shouldn't be considered integration tests and be executed only in a later stage of the build cycle.

**Comment by cyrille-artho** [comment]
Let's try to get the paths fixed by eliminating hard-coded paths wherever possible.
Perhaps we can define some compile-time settings for this.
The paths will change again with JDK 9/10, so having a single configuration entry for them would be good.

**Comment by jeandersonbc** [comment]
Alright, I'm closing this issue for now, since changes were merged.
