### ISSUE TITLE
Assistance Needed with Deadlock Detection in JPF

### ISSUE THREAD

**Issue by bupt01** [javapathfinder/jpf-core#464]
I encountered an issue where JPF did not detect a deadlock in the following code. I would appreciate any insights or guidance you could provide regarding this matter.

#### Buffer.java

```java

1. package nested_monitor;

2. public interface Buffer {

3.     public void put(Object o)

4.        throws InterruptedException; 

5.     public Object get()

6.        throws InterruptedException;       

7. }

```

#### NestedMonitor.java

```java

1. package nested_monitor;

2. class SemaBuffer implements Buffer {

3.   protected int size;

4.   Semaphore full; 

5.   Semaphore empty;

6.   SemaBuffer(int size) {

7.     this.size = size; 

8.     full = new Semaphore(0);

9.     empty = new Semaphore(size);

10.   }

11.   synchronized public void put(Object o)

12.               throws InterruptedException {

13.     empty.down();

14.     full.up();

15.   }

16.   synchronized public Object get()

17.                throws InterruptedException {

18.     full.down();

19.     empty.up();

20.     return (null); 

21.   }

22. }

23. public class NestedMonitor {

24.   static int SIZE = 5; 

25.   static Buffer buf;

26.     public static void main(String[] args) {

27.         buf = new SemaBuffer(SIZE);

28.         new Producer(buf).start();

29.         new Consumer(buf).start();

30.     }

31. }

32. class Producer extends Thread {

33.     Buffer buf;

34.     Producer(Buffer b) { buf = b; }

35.     public void run() {

36.       try {

37.         while (true) {

38.             buf.put(null); 

39.         }

40.       } catch (InterruptedException e) { }

41.     }

42. }

43. class Consumer extends Thread {

44.     Buffer buf;

45.     Consumer(Buffer b) { buf = b; }

46.     public void run() {

47.       try {

48.         while (true) {

49.             buf.get(); 

50.         }

51.       } catch (InterruptedException e) { }

52.     }

53. }

```

#### Semaphore.java

```java

1. package nested_monitor;

2. public class Semaphore {

3.     private int value;

4.     public Semaphore(int initial) {

5.         value = initial;

6.     }

7.     synchronized public void up() {

8.         ++value;

9.         notifyAll();  

10.     }

11.     synchronized public void down() throws InterruptedException {

12.         while (value == 0) wait();

13.         --value;

14.     }

15. }

```

Despite my efforts, I am unsure why JPF does not detect a deadlock with this code. Any help or advice you could offer would be greatly appreciated.

**Comment by cyrille-artho** [comment]
What is the output that you get, and what output do you expect? If one thread is sometimes blocked, that's not a deadlock. It seems like there is always one thread that can continue, at least after an initial quick look at your code.

**Comment by bupt01** [comment]
Is it true that only holding one lock and waiting for another lock to be released can be considered a deadlock? In this program, if the consumer executes first, it will block at line 12 (wait) in Semaphore.java. For the consumer to continue, the producer must execute line 9 (notifyAll()) in Semaphore.java. However, since the producer cannot execute the put() method, all threads will be in a blocked state. Can this situation be considered a deadlock? Can it be identified like the classic scenario of T1: lock(l1); lock(l2); and T2: lock(l2); lock(l1);?

**Comment by cyrille-artho** [comment]
JPF can find deadlocks in such situations, too. Can you please share your code in a way that it can be copied and ran locally? The most efficient way would be a small git repo with all the code and JPF configuration set up.

**Comment by bupt01** [comment]
Thank you, I found a stupid error in one of my Settings

**Comment by cyrille-artho** [comment]
Thank you for confirming. We can close this issue then.
