### ISSUE TITLE
java.lang.NoSuchMethodException: SharedSecrets.setJavaNetInetAddressAccess

### ISSUE THREAD

**Issue by ChangWan723** [javapathfinder/jpf-core#482]
I encountered an issue when using JPF to verify a piece of code on `JDK 11.0.24`. The error occurs when attempting to create a `java.net.Socket` object. The program fails with a `java.lang.NoSuchMethodException` related to `jdk.internal.misc.SharedSecrets` (there really isn't the method `setJavaNetInetAddressAccess` in JPF's `SharedSecrets`). It seems that JPF may not support `Socket` in `JDK 11`. Are there any known workarounds or updates in JPF that deal with such issues? 

---

Test Code:
```java
public void test() {
    if (verifyNoPropertyViolation()) {
        try {
            Socket socket = new Socket("localhost", 12345); // error location
            // ...
            // ...
        } catch (Exception e) {
            // ...
        }
    }
}
```

Error Message:

```
====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodException: jdk.internal.misc.SharedSecrets.setJavaNetInetAddressAccess(Ljdk/internal/misc/JavaNetInetAddressAccess;)V
	at java.net.InetAddress.<clinit>(java/net/InetAddress.java:327)
	at java.net.InetSocketAddress.<init>(java/net/InetSocketAddress.java:220)
	at java.net.Socket.<init>(java/net/Socket.java:231)
	at project.jpf.Test.test(project/jpf/Test.java:28)
```

**Comment by Harsh4902** [comment]
@ChangWan723 I think still there is no support for `java.net.InetAddress` class in JPF for JDK 11.

**Comment by Harsh4902** [comment]
@cyrille-artho Can some configuration of jpf-nhandler help for this?

**Comment by cyrille-artho** [comment]
In this case, you have to provide a method to register `InetAddress` in `SharedSecrets`. Simple copy one of the templates.
