### ISSUE TITLE
error: [junit] cannot load system class java.lang.Object

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#50]
When running tests compiled with Java 9 and later, results in the run time errors look like the following:

    [junit] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
    [junit] Running TypeNameTest
    [junit]   running jpf with args:
    [junit] [SEVERE] cannot load system class java.lang.Object
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.521 sec
    [junit] gov.nasa.jpf.vm.ClassInfoException: class not found: java.lang.Object
    [junit] 	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
    [junit] 	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
    [junit] 	at gov.nasa.jpf.vm.VM.getStartupSystemClassInfos(VM.java:445)
    [junit] 	at gov.nasa.jpf.vm.VM.initializeMainThread(VM.java:564)
    [junit] 	at gov.nasa.jpf.vm.SingleProcessVM.initialize(SingleProcessVM.java:130)
    [junit] 	at gov.nasa.jpf.JPF.run(JPF.java:611)
    [junit] 	at gov.nasa.jpf.util.test.TestJPF.createAndRunJPF(TestJPF.java:675)
    [junit] 	at gov.nasa.jpf.util.test.TestJPF.noPropertyViolation(TestJPF.java:806)
    [junit] 	at gov.nasa.jpf.util.test.TestJPF.verifyNoPropertyViolation(TestJPF.java:830)
    [junit] 	at TypeNameTest.testArrayCloning(TypeNameTest.java:58)

Possibly because of the new Module System, the class URI of the generated  .class files in the build destination directory are different than previously, which makes JPF classloader to fail resolve the model classes from jpf-classes.jar

JDK 8

    build/classes/
    ├── java
    │   ├── io
    │   ├── lang
    │   │   ├── annotation
    │   │   ├── ref
    │   │   └── reflect
    
JDK 9/10
    
    build/classes/
    ├── java.base
    │   ├── java
    │   │   ├── io
    │   │   ├── lang
    │   │   │   ├── annotation
    │   │   │   ├── ref
    │   │   │   └── reflect

https://travis-ci.org/javapathfinder/jpf-core/builds/381450375#L3059-L3073

**Comment by cyrille-artho** [comment]
Thanks!
Your patch includes, in addition to java.base, also java.logging and "gov/nasa/jpf/*.class", "org/junit/*.class". Are those also necessary? Will the test(s) run successfully without them?
I am rather reluctant with putting JUnit's classes into jpf-classes.jar (that's not where they should be), and I think the same goes for JPF's classes.

**Comment by gayanW** [comment]
@cyrille-artho 
I think you're right. So I ran tests with Java 8 on the master branch without including either `gov/nasa/jpf/.class`, or JUnit classes into jpf-classes.jar. And it doesn't make any difference to the test results. They all do pass as before. I'm not sure why these being added before though.

**Comment by cyrille-artho** [comment]
Sorry to appear to be nitpicking, but can you please try to remove the line removal on line 431? This creates a second hunk in the patch. Simply add an empty line again, and the resulting pull request will be smaller.
In general, patches without white space changes are easier to merge and handle.

**Comment by gayanW** [comment]
Np. Done.
