### ISSUE TITLE
Improve verbosity level on Travis for Gradle builds

### ISSUE THREAD

**Issue by jeandersonbc** [javapathfinder/jpf-core#54]
I noticed that Travis is not displaying properly the Gradle output.
This is probably due to some terminal environment on Travis.

**Comment by jeandersonbc** [comment]
For reference: https://travis-ci.org/javapathfinder/jpf-core/builds/381901115

**Comment by cyrille-artho** [comment]
Yes, the build output looks fine, but there is no output from JUnit visible.

**Comment by jeandersonbc** [comment]
I tested my changes on Travis. Here it is what it looks like:
https://travis-ci.org/jeandersonbc/jpf-core/builds/382144004

Turns out it wasn't something directly related to the Travis environment at all.
I was used to checking the generated HTML reports and didn't notice that Gradle omitted JUnit output by default.
