### ISSUE TITLE
Add support to Jar tasks on Gradle Build

### ISSUE THREAD

**Issue by jeandersonbc** [javapathfinder/jpf-core#57]
The current Gradle support covers all original compilation tasks and test execution.
Another important task that must be covered, and it is between `compile` and `test` is the `build` task.
The build task is responsible for generating some important jars.

**Comment by jeandersonbc** [comment]
According to my python script that compares the Ant and Gradle execution, I'm missing two jars:

```
$ python3 main.py
Running command "ant clean build"
Finished in 18.53 secs
Running command "./gradlew clean buildJars --info"
Finished in 9.52 secs
Total files: 1839
Common files: 1836
Missing files: 3
 - /Users/jeandersonbc/projects/jpf/jpf-core/build/RunJPF.jar
 - /Users/jeandersonbc/projects/jpf/jpf-core/build/RunTest.jar
 - /Users/jeandersonbc/projects/jpf/jpf-core/build/classes/java/nio/package-info.class
```

I'm working on those two missing jars.
I don't know why the gradle build is not copying the `package-info.class` file into the build directory, but I believe this is not critical right now.

**Comment by gayanW** [comment]
`package-info.class` seems to go in `jpf-classes.jar`

**Comment by cyrille-artho** [comment]
Looks like it is done, but it's good to have a test that depends on build.properties being in the right place. You can make a new issue for that, in which case I can close this one.

**Comment by jeandersonbc** [comment]
Sure! I'm opening a new issue for that. Since changes are merged, I think it's ok to close this one now.
