### ISSUE TITLE
Remove countStackFrames() in test

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#62]
Among the many remaining compiler warnings about deprecated code, one stands out:

`src/tests/gov/nasa/jpf/test/mc/basic/StackDepthCheckerTest.java:50: warning: [removal] countStackFrames() in Thread has been deprecated and marked for removal`

Because this API was marked for removal, it may no longer be part of Java 11, which comes out soon.

Having the stack frame depth in the test case is actually not very important, so I think it is best to simply remove that line. The stack depth count will be off by a constant offset, but that is not important.

While cleaning up that test, I would also remove this code:
`
    n--; // not that we ever get here
    System.out.print("exited foo() at level ");
    System.out.println(n);
`
and replace it with `// this function never returns`

**Comment by gayanW** [comment]
Yeah I see that the value of n is not important. I don't understand what you meant by 

> The stack depth count will be off by a constant offset

as n will be 0 when testInfiniteRecursion test starts. Should I also need change the class name 'StackDepthCheckerTest' to something like 'InfiniteRecursionTest' as the former doesn't seem to make much sense?

**Comment by cyrille-artho** [comment]
Hi Gayan,
Actually, the stack depth count would be non-zero at the beginning: a lot of methods are called (the JUnit test runner, JPF), before testInfiniteRecursion is called. We will not count these if we just have n set to 0 (at class initialization) rather than the result of t.countStackFrames().
However, the number was used mostly for aesthetic purposes, so we can start counting from 0.
The test class name makes sense, though: The test starts a JPF run with specific options:
```
verifyUnhandledException("java.lang.StackOverflowError",
        "+listener=.listener.StackDepthChecker", "+sdc.max_stack_depth=42"
```
Therefore, it checks if the listener can catch the infinite recursion at depth 42.

**Comment by gayanW** [comment]
Thanks. Always learning :)
