### ISSUE TITLE
warning: Unsafe is internal proprietary API

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#68]
Compiler warning 'Unsafe is internal proprietary API and may be removed in a future release' when build with JDK 9 and later:

    [javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:32: warning: Unsafe is internal proprietary API and may be removed in a future release
    [javac] import sun.misc.Unsafe;
    [javac]                ^
    [javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:93: warning: Unsafe is internal proprietary API and may be removed in a future release
    [javac]   private static Unsafe unsafe;
    [javac]                  ^
    [javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:99: warning: Unsafe is internal proprietary API and may be removed in a future release
    [javac]       Field singletonField = Unsafe.class.getDeclaredField("theUnsafe");
    [javac]                              ^
    [javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:101: warning: Unsafe is internal proprietary API and may be removed in a future release

Travis log:
https://travis-ci.org/javapathfinder/jpf-core/builds/385057883#L2471-L2483

**Comment by cyrille-artho** [comment]
This is a very difficult case. I would postpone that one until the easier things are resolved.

You're welcome to look for possible replacements of Unsafe.getFieldOffset. I couldn't find any right away with a quick search. If you can't find something, you can leave this code as is, as it won't get removed yet for Java 11.

**Comment by gayanW** [comment]
Please see the PR. It however requires a change in javac target for src/peers in build.xml

**Comment by cyrille-artho** [comment]
Ah, at this level, the fix is good. I don't think there is a permanent (non-internal) API yet that could replace this one. So I close this issue for now.
