### ISSUE TITLE
warning: [deprecation] getPackage(String) in ClassLoader has been deprecated

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#71]
Deprecation warning 'getPackage(String) in ClassLoader has been deprecated' when build with JDK 9 and later:

    [javac] /home/travis/build/javapathfinder/jpf-core/src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java:68: warning: [deprecation] getPackage(String) in ClassLoader has been deprecated
    [javac] 	protected Package getPackage(String name) {
    [javac] 	                  ^
    [javac] /home/travis/build/javapathfinder/jpf-core/src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java:69: warning: [deprecation] getPackage(String) in ClassLoader has been deprecated
    [javac]       return super.getPackage(name);
    [javac]                   ^

https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java#L67-L70

Travis log:
https://travis-ci.org/javapathfinder/jpf-core/builds/385707808#L2456-L2461

References:
[cr.openjdk.java.net/~iris/se/10/latestSpec/api/java/lang/ClassLoader.html#getPackage(java.lang.String)](http://cr.openjdk.java.net/~iris/se/10/latestSpec/api/java/lang/ClassLoader.html#getPackage(java.lang.String))

**Comment by gayanW** [comment]
Simplest solution would be just to annotate the override method with     `@SuppressWarnings("deprecation")`

The overridden method is being called in here:
https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java#L482-L497

Another possible solution would be to refactor `cl.getPackage` to use the method `ClassLoader#getDefinedPackage` instead. But as the name suggests the test is written specially for getPackage.

**Comment by cyrille-artho** [comment]
Perhaps the test still passes when using `getDefinedPackage`. In that case, changing the method is the best way (note that `getDefinedPackage` was introduced in Java 9).
