### ISSUE TITLE
warning: ChoiceGeneratorBase() in ChoiceGeneratorBase has been deprecated

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#72]
Compiler warning "[deprecation] ChoiceGeneratorBase() in ChoiceGeneratorBase has been deprecated" when build with JDK 9 and later.

    [javac] /home/travis/build/javapathfinder/jpf-core/src/main/gov/nasa/jpf/vm/choice/PermutationCG.java:35: warning: [deprecation] ChoiceGeneratorBase() in ChoiceGeneratorBase has been deprecated
    [javac]   public PermutationCG (PermutationGenerator pg){
    [javac]                                                 ^

https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/main/gov/nasa/jpf/vm/choice/PermutationCG.java#L30-L43

Default constructor of the super class 'gov.nasa.jpf.vm.ChoiceGeneratorBase' is marked deprecated, but the constructor PermutationCG (PermutationGenerator) is not, thus resulting in the warning.

https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/main/gov/nasa/jpf/vm/ChoiceGeneratorBase.java#L99-L110

Travis log:
https://travis-ci.org/javapathfinder/jpf-core/builds/385707808#L2425-L2427

**Comment by cyrille-artho** [comment]
Actually, neither of the default constructors is used by jpf-core itself (internally).
However, some of the other projects may use it.
I would consider removing the default constructor, but we should give extension writers time to adapt.
Therefore, I'd mark **both** constructors (PermutationCG and ChoiceGeneratorBase) with
`@Deprecated(forRemoval=<boolean>)`
and would also insert an annotation that suppresses this warning in the constructor of PermutationCG.
