### ISSUE TITLE
Add test to check if the "build.properties" file is missing in jpf.jar

### ISSUE THREAD

**Issue by jeandersonbc** [javapathfinder/jpf-core#75]
As discussed with @cyrille-artho, we should add a test to verify if an expected `build.properties` file is missing in `jpf.jar` file.

**Comment by jeandersonbc** [comment]
Reminder: there is a `getRepositoryInfo()` in gov/nasa/jpf/report/Reporter.java, which returns null if build.properties cannot be found.

**Comment by jeandersonbc** [comment]
After adding a minimal main to debug `gov.nasa.jpf.report.Reporter` (check [here](https://github.com/jeandersonbc/jpf-core/commit/726cd4795354c7cb571f2d7e3c851e49898ba723)), I noticed that `getRepositoryInfo()` is called only in `getJPFBanner()`:

```{Java}
  public String getJPFBanner () {
    // ...
    String rev = getRevision();
    if (rev != null){
      sb.append(" (rev ");
      sb.append(rev);
      sb.append(')');
    }
    // ...
    if (conf.getBoolean("report.show_repository", false)) {
      String repInfo =  getRepositoryInfo();
      if (repInfo != null) {
        sb.append( repInfo);
      }
    }
    return sb.toString();
  }
```

`getRevision()` reads a hash from `.version` (currently missing) and a similar thing goes with `getRepositoryInfo()` with `build.properties` (reads outdated info from an old .version file in the repository).

I guess the way to work on this issue is to create a `ReportTest` test and maybe add a mocked .version and build.properties file to test wheater `getRespositoryInfo` and `getRevision` output what is expected to output.

Note that without these mocked `.version` and `build.properties` file, we will have a test that won't be able to do much except check if the path `.../.../.version` and `.../.../.../build.properties` exists: both files are "revision-dependent".

@cyrille-artho and @wvisser - I guess just checking if both paths exist doesn't justify a new test in the test suite. I will work on my suggestion (ReportTest + mocked files) and submit a pull request for review, ok?

**Comment by cyrille-artho** [comment]
Hi Jeanderson,
One way to do this could be a test that fails if either file is missing.

That would require getting the hash to work again (this stopped working when hg was replaced by git) for the test to pass.

--
Regards,
Cyrille Artho

**Comment by cyrille-artho** [comment]
Great job, thanks!
