### ISSUE TITLE
warning: Reflection is internal proprietary API and may be removed

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#81]
Deprecation warning 

    'Reflection is internal proprietary API and may be removed in a future release' 

when build with JDK 9 and later:

    [javac] /home/travis/build/javapathfinder/jpf-core/src/tests/gov/nasa/jpf/test/vm/reflection/ReflectionTest.java:34: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac]       Class<?> callerCls = sun.reflect.Reflection.getCallerClass(0); // that would be getCallerClass()
    [javac]                                       ^

Travis log:
https://travis-ci.org/javapathfinder/jpf-core/builds/389306467#L2485-L2508

References:
https://www.logicbig.com/tutorials/core-java-tutorial/java-9-changes/stack-walker-caller.html

**Comment by gayanW** [comment]
If we are to use the StackWalker instead of calling sun.reflect.Reflection.getCallerClass, I think it will make sense to refactor the name of the test class from 'gov.nasa.jpf.test.**vm.reflection.ReflectionTest**' to 'gov.nasa.jpf.test.**java.lang.StackWalkerTest**'

For your reference:
https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/tests/gov/nasa/jpf/test/vm/reflection/ReflectionTest.java#L24-L36

**Comment by cyrille-artho** [comment]
Yes, please update the class name for consistency.
