### ISSUE TITLE
ClassInfoException when running tests - Java 10

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#94]
Tests executes through JPF fails with ClassInfoException when running under Java 9/10.

### Example: Running gov.nasa.jpf.test.basic.HarnessTest

    [junit] gov.nasa.jpf.vm.ClassInfoException: class not found: java.io.Serializable
    [junit]     at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
    [junit]     at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
    [junit]     at gov.nasa.jpf.vm.SystemClassLoaderInfo.loadClass(SystemClassLoaderInfo.java:182)
    [junit]     at gov.nasa.jpf.vm.ClassInfo.resolveReferencedClass(ClassInfo.java:2414)
    [junit]     at gov.nasa.jpf.vm.ClassInfo.loadInterfaces(ClassInfo.java:2366)
    [junit]     at gov.nasa.jpf.vm.ClassInfo.resolveClass(ClassInfo.java:2383)
    [junit]     at gov.nasa.jpf.vm.ClassInfo.resolveAndLink(ClassInfo.java:548)
    [junit]     at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:624)
    [junit]     at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:58)
    [junit]     at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:33)
    [junit]     at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:353)
    [junit]     at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
    [junit]     at gov.nasa.jpf.vm.VM.getStartupSystemClassInfos(VM.java:445)
    [junit]     at gov.nasa.jpf.vm.VM.initializeMainThread(VM.java:564)
    [junit]     at gov.nasa.jpf.vm.SingleProcessVM.initialize(SingleProcessVM.java:130)
    [junit]     at gov.nasa.jpf.JPF.run(JPF.java:611)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.createAndRunJPF(TestJPF.java:675)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.unhandledException(TestJPF.java:849)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.verifyUnhandledException(TestJPF.java:903)
    [junit]     at gov.nasa.jpf.test.basic.HarnessTest.verifyNullPointerException(HarnessTest.java:54)

ClassInfoException is thrown in here:

https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/main/gov/nasa/jpf/vm/ClassLoaderInfo.java#L316-L372

### Possible causes

As stated in the JDK 9 Release Notes the system property sun.boot.class.path has been removed. This makes JPF to fail resolve standard Java classes.

https://github.com/javapathfinder/jpf-core/blob/18a0c42de3e80be0c2ddcf0d212e376e576fcda0/src/main/gov/nasa/jpf/vm/ClassInfo.java#L1676-L1680

**References** 
http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html
https://stackoverflow.com/q/50451536/3647002

---

Implementation for the class URL generation would also need to be updated.

https://github.com/javapathfinder/jpf-core/blob/a9bc9081ebda74eb6ee5451d2b719405db3a955c/src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java#L74-L77

In the earlier versions path to standard class would be like:

> jar:file:/path/to/jjre/lib/rt.jar!/java/lang/Object.class

With the module system:

> jrt:/**java.base**/java/lang/Object.class

**Comment by cyrille-artho** [comment]
You can replace `sun.boot.class.path` with a list of all relevant jar files in `System.getProperty("java.home") + java.io.File.separator + "lib"`

There are many .jar files in that directory; the ones that are needed for bootstrapping the JVM in Java 8 are (on Mac OS X):

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/resources.jar/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/sunrsasign.jar/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jsse.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jce.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/charsets.jar/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jfr.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/classes
```

However, the list may be different for newer versions of Java, so it is probably best to look through all .jar files in java.home + "/lib".

**Comment by cyrille-artho** [comment]
We have to use java.lang.Classloader to load all internal resources, as the format of the internal storage of the base libraries is not defined and subject to change.

It seems the right way to do this is to go through the module layer:
```
Module m = ModuleLayer.boot().findModule("java.base"); // returns Option<Module>
m.get().getResourceAsStream("java.lang.Object");
```

**Comment by cyrille-artho** [comment]
It seems we have to adapt JPF at various levels for this: JPF.java, to use the right classloader; JVMClassFileContainer, perhaps subclasses as JModClassFileContainer, which can delegate to Module.getResourceAsStream and such; and we have to make sure that the base classes are found and loaded without implementation-specific user configuration.
