### ISSUE TITLE
Use git describe --tags instead of git hash for detailed version info

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#95]
We currently use the git hash to identify the exact version, but the usual way nowadays seems to be the output of `git describe --tags`. Using this will be simpler and more descriptive than the git hash.

**Comment by jeandersonbc** [comment]
Interesting. I wasn't aware of this command.
Correct me if I'm wrong, but we need to start tagging our releases if we want to use this command, right?
I'm totally in favor of it.

**Comment by cyrille-artho** [comment]
Yes, using this command requires tagging the releases. With `git describe`, releases that are tagged get a "clean" tag (such as "JPF-9.1"), while development snapshots get a "-N" and a git hash after it, e.g., "RELEASE-3.2-14-gf0d8a11".
We need to decide whether to call the tags "JPF-x.y" or "RELEASE-x.y", and when to increment the minor version number.
I think it's good practice to keep the major version number in sync with the Java version that we support.

**Comment by cyrille-artho** [comment]
The test in src/tests/ReporterResourcesTest.java should simply check if the .version info is non-empty, so we are not dependent on the exact mechanism that generates the version info.
