### ISSUE TITLE
Errors coming with these versions jdk1.8.0_101, _102, _111.

### ISSUE THREAD

**Issue by knl97** [javapathfinder/jpf-core#96]
### I am using _net beans for building_ it up with the version **101** (basic) and then the following errors encounter 

- jpf-core-master\src\classes\sun\misc\SharedSecrets.java:60: error: cannot find symbol
  private static JavaOISAccess javaOISAccess;
  symbol:   class JavaOISAccess
  location: class SharedSecrets

- jpf-core-master\src\classes\sun\misc\SharedSecrets.java:162:
  error: cannot find symbol
  public static void setJavaOISAccess(JavaOISAccess access) {
  symbol:   class JavaOISAccess
  location: class SharedSecrets

- jpf-core-master\src\classes\sun\misc\SharedSecrets.java:166:
  error: cannot find symbol
  public static JavaOISAccess getJavaOISAccess() {
  symbol:   class JavaOISAccess
  location: class SharedSecrets
Note: Some input files use internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.

Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 18 seconds)

@jeandersonbc  thanks for considering and understanding my problem.

**Comment by gayanW** [comment]
Use a newer JDK 8 release. JDK 8u171 should work.
