### ISSUE TITLE
Fails to handle native calls to jdk.internal.misc.Unsafe - Java 10

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#99]
NoSuchMethodError, and UnsatisfiedLinkError exceptions are thrown while running tests under Java 10  

**NoSuchMethodError**

    [junit] gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
    [junit] java.lang.NoSuchMethodError: jdk.internal.misc.Unsafe.objectFieldOffset(Ljava/lang/Class;Ljava/lang/String;)J
    [junit]     at java.util.concurrent.ConcurrentHashMap.<clinit>(ConcurrentHashMap.java:6377)
    [junit]     at java.util.Properties.<init>(Properties.java:201)
    [junit]     at java.util.Properties.<init>(Properties.java:168)
    [junit]     at java.lang.System.<clinit>(System.java:46)

**UnsatisfiedLinkError**

    [junit] gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
    [junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.Unsafe.objectFieldOffset
    [junit]     at jdk.internal.misc.Unsafe.objectFieldOffset(gov.nasa.jpf.vm.JPF_jdk_internal_misc_Unsafe)
    [junit]     at java.util.concurrent.ConcurrentHashMap.<clinit>(ConcurrentHashMap.java:6377)
    [junit]     at java.util.Properties.<init>(Properties.java:201)
    [junit]     at java.util.Properties.<init>(Properties.java:168)
    [junit]     at java.lang.System.<clinit>(System.java:46)

Exceptions are thrown for the following methods:
-   public native long objectFieldOffset(Class<?> c, String name);
-   public final native boolean compareAndSetInt(Object o, long offset, int expected, int x);
-   public final native boolean compareAndSetLong(Object o, long offset, long expected, long x);
-   public final native boolean compareAndSetObject(Object o, long offset, Object expected, Object x);

-   public final native Object getObjectAcquire(Object o, long offset);

**Proposed solution:**

These two exceptions can be fixed by adding the missing methods in the Unsafe model class and their corresponding native peer methods (in JPF_jdk_internal_misc_Unsafe) subsequently.

**Comment by gayanW** [comment]
I was able to write native methods for the above specified methods (mainly through delegation to existing methods) except for objectFieldOffset(Class<?> c, String name); which I'm not sure how to.

```
  /**
   * NativePeer method for {@link jdk.internal.misc.Unsafe#getObjectAcquire(Object, long)}
   * Acquire version of {@link #getObjectVolatile(Object, long)}
   */
  @MJI
  public int getObjectAcquire__Ljava_lang_Object_2J__Ljava_lang_Object_2(MJIEnv env, int unsafeRef, int oRef, long offset) {
      return getObjectVolatile__Ljava_lang_Object_2J__Ljava_lang_Object_2(env, unsafeRef, oRef, offset);
  }

  /**
   * NativePeer method for {@link jdk.internal.misc.Unsafe#compareAndSetObject(java.lang.Object, long, java.lang.Object, java.lang.Object)}
   */
  @MJI
  public boolean compareAndSetObject__Ljava_lang_Object_2JLjava_lang_Object_2Ljava_lang_Object_2__Z(MJIEnv env, int unsafeRef, int oRef, long offset, int expectedRef, int xRef) {
    int actual = getObject__Ljava_lang_Object_2J__Ljava_lang_Object_2(env, unsafeRef, oRef, offset);
    if (actual == expectedRef) {
      putObject__Ljava_lang_Object_2JLjava_lang_Object_2__V(env, unsafeRef, oRef, offset, xRef);
      return true;
    }
    return false;
  }
  /**
   * NativePeer method for {@link jdk.internal.misc.Unsafe#compareAndSetInt(java.lang.Object, long, int, int)}
   */
  @MJI
  public boolean compareAndSetInt__Ljava_lang_Object_2JII__Z (MJIEnv env, int unsafeRef,
                                                               int oRef, long offset, int expected, int x) {
    int actual = getInt__Ljava_lang_Object_2J__I(env, unsafeRef, oRef, offset);
    if (actual == expected) {
      putInt__Ljava_lang_Object_2JI__V(env, unsafeRef, oRef, offset, x);
      return true;
    }
    return false;
  }

  /**
   * NativePeer method for {@link jdk.internal.misc.Unsafe#compareAndSetLong(Object, long, long, long)}
   */
  @MJI
  public boolean compareAndSetLong__Ljava_lang_Object_2JJJ__Z (MJIEnv env, int unsafeRef,
                                                              int oRef, long offset, long expected, long x) {
    long actual = getLong__Ljava_lang_Object_2J__J(env, unsafeRef, oRef, offset);
    if (actual == expected) {
      putLong__Ljava_lang_Object_2JJ__V(env, unsafeRef, oRef, offset, x);
      return true;
    }
    return false;
  }
```

**Comment by gayanW** [comment]
We already have a NativePeer method for **Unsafe#objectFieldOffset(java.lang.reflect.Field)**:

https://github.com/javapathfinder/jpf-core/blob/d595544a88bad44ea2ddedbc27e3e664a5b920fd/src/peers/gov/nasa/jpf/vm/JPF_sun_misc_Unsafe.java#L55-L65

But now it complains about the missing method Unsafe#objectFieldOffset(java.lang.Class, java.lang.String).

May be we could add a peer method for it similar to the following..?
```
  @MJI
  public long objectFieldOffset__Ljava_lang_Class_2Ljava_lang_String_2__J (MJIEnv env, int unsafeRef, int clsRef, int sRef) {
    String fname = env.getStringObject(sRef);                                                                                                          
    return env.getReferredClassInfo(clsRef).getInstanceField(fname).getStorageOffset();                                                                
  }
```

**Note**: The written method implementations are guess work based on existing methods in JPF_jdk_internal_misc_Unsafe, MJIEnv, and Unsafe from OpenJDK and may probably require changes.

**Comment by cyrille-artho** [comment]
I think the commented-out code in `objectFieldOffset` above does the right thing. It returns the offset that is used by `put{Long,Int,Object}` later on. Your change 42436676a84b946d6be63edc150b39245354a6c9 has the right variant.
It may be good to have a few tests for the sequential case; as the native peers in JPF execute atomically, we probably don't need to bother about an elaborate concurrent test, unless that's easy to write.
Two tests for `compareAndSet...` (1) check the case where the value matches, (2) where it does not match, and reads the new state of the changed value using other methods, will do to ensure that these methods work correctly. `objectFieldOffset` would therefore be tested indirectly, via `compareAndSet`.
